/**
 *	@file	unit_test_qvm_vector_swizzle.cpp
 *
 *	@brief	swizzling のテスト
 */

#include <hamon/qvm/vector/vector.hpp>
#include <hamon/qvm/vector/operators.hpp>
#include <hamon/type_traits/is_same.hpp>
#include "constexpr_test.hpp"
#include "vector_test.hpp"

namespace hamon_qvm_test
{

namespace vector_test
{

template <typename T>
void Vector2SwizzleTest()
{
	using vector2 = hamon::qvm::vector<T, 2>;
	using vector3 = hamon::qvm::vector<T, 3>;
	using vector4 = hamon::qvm::vector<T, 4>;

	HAMON_CONSTEXPR vector2 v(1, 2);

	static_assert(hamon::is_same<vector4, decltype(v.xxxx())>::value, "");
	static_assert(hamon::is_same<vector4, decltype(v.yyyy())>::value, "");
	static_assert(hamon::is_same<vector3, decltype(v.xxx())>::value, "");
	static_assert(hamon::is_same<vector3, decltype(v.yyy())>::value, "");
	static_assert(hamon::is_same<vector2, decltype(v.xx())>::value, "");
	static_assert(hamon::is_same<vector2, decltype(v.yy())>::value, "");

	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 1, 1), v.xxxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 1, 2), v.xxxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 2, 1), v.xxyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 2, 2), v.xxyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 1, 1), v.xyxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 1, 2), v.xyxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 2, 1), v.xyyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 2, 2), v.xyyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 1, 1), v.yxxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 1, 2), v.yxxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 2, 1), v.yxyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 2, 2), v.yxyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 1, 1), v.yyxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 1, 2), v.yyxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 2, 1), v.yyyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 2, 2), v.yyyy());

	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 1, 1), v.xxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 1, 2), v.xxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 2, 1), v.xyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 2, 2), v.xyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 1, 1), v.yxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 1, 2), v.yxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 2, 1), v.yyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 2, 2), v.yyy());

	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(1, 1), v.xx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(1, 2), v.xy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(2, 1), v.yx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(2, 2), v.yy());
}

template <typename T>
void Vector3SwizzleTest()
{
	using vector2 = hamon::qvm::vector<T, 2>;
	using vector3 = hamon::qvm::vector<T, 3>;
	using vector4 = hamon::qvm::vector<T, 4>;

	HAMON_CONSTEXPR vector3 v(1, 2, 3);

	static_assert(hamon::is_same<vector4, decltype(v.xxxx())>::value, "");
	static_assert(hamon::is_same<vector4, decltype(v.zzzz())>::value, "");
	static_assert(hamon::is_same<vector3, decltype(v.xxx())>::value, "");
	static_assert(hamon::is_same<vector3, decltype(v.xyz())>::value, "");
	static_assert(hamon::is_same<vector2, decltype(v.xx())>::value, "");
	static_assert(hamon::is_same<vector2, decltype(v.xy())>::value, "");

	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 1, 1), v.xxxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 1, 2), v.xxxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 1, 3), v.xxxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 2, 1), v.xxyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 2, 2), v.xxyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 2, 3), v.xxyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 3, 1), v.xxzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 3, 2), v.xxzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 3, 3), v.xxzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 1, 1), v.xyxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 1, 2), v.xyxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 1, 3), v.xyxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 2, 1), v.xyyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 2, 2), v.xyyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 2, 3), v.xyyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 3, 1), v.xyzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 3, 2), v.xyzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 3, 3), v.xyzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 1, 1), v.xzxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 1, 2), v.xzxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 1, 3), v.xzxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 2, 1), v.xzyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 2, 2), v.xzyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 2, 3), v.xzyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 3, 1), v.xzzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 3, 2), v.xzzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 3, 3), v.xzzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 1, 1), v.yxxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 1, 2), v.yxxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 1, 3), v.yxxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 2, 1), v.yxyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 2, 2), v.yxyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 2, 3), v.yxyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 3, 1), v.yxzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 3, 2), v.yxzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 3, 3), v.yxzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 1, 1), v.yyxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 1, 2), v.yyxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 1, 3), v.yyxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 2, 1), v.yyyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 2, 2), v.yyyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 2, 3), v.yyyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 3, 1), v.yyzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 3, 2), v.yyzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 3, 3), v.yyzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 1, 1), v.yzxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 1, 2), v.yzxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 1, 3), v.yzxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 2, 1), v.yzyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 2, 2), v.yzyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 2, 3), v.yzyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 3, 1), v.yzzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 3, 2), v.yzzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 3, 3), v.yzzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 1, 1), v.zxxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 1, 2), v.zxxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 1, 3), v.zxxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 2, 1), v.zxyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 2, 2), v.zxyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 2, 3), v.zxyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 3, 1), v.zxzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 3, 2), v.zxzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 3, 3), v.zxzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 1, 1), v.zyxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 1, 2), v.zyxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 1, 3), v.zyxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 2, 1), v.zyyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 2, 2), v.zyyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 2, 3), v.zyyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 3, 1), v.zyzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 3, 2), v.zyzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 3, 3), v.zyzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 1, 1), v.zzxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 1, 2), v.zzxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 1, 3), v.zzxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 2, 1), v.zzyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 2, 2), v.zzyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 2, 3), v.zzyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 3, 1), v.zzzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 3, 2), v.zzzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 3, 3), v.zzzz());

	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 1, 1), v.xxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 1, 2), v.xxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 1, 3), v.xxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 2, 1), v.xyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 2, 2), v.xyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 2, 3), v.xyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 3, 1), v.xzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 3, 2), v.xzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 3, 3), v.xzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 1, 1), v.yxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 1, 2), v.yxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 1, 3), v.yxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 2, 1), v.yyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 2, 2), v.yyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 2, 3), v.yyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 3, 1), v.yzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 3, 2), v.yzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 3, 3), v.yzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 1, 1), v.zxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 1, 2), v.zxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 1, 3), v.zxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 2, 1), v.zyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 2, 2), v.zyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 2, 3), v.zyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 3, 1), v.zzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 3, 2), v.zzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 3, 3), v.zzz());

	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(1, 1), v.xx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(1, 2), v.xy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(1, 3), v.xz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(2, 1), v.yx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(2, 2), v.yy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(2, 3), v.yz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(3, 1), v.zx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(3, 2), v.zy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(3, 3), v.zz());
}

template <typename T>
void Vector4SwizzleTest()
{
	using vector2 = hamon::qvm::vector<T, 2>;
	using vector3 = hamon::qvm::vector<T, 3>;
	using vector4 = hamon::qvm::vector<T, 4>;

	HAMON_CONSTEXPR vector4 const v(1, 2, 3, 4);

	static_assert(hamon::is_same<vector4, decltype(v.xxxx())>::value, "");
	static_assert(hamon::is_same<vector4, decltype(v.xyzw())>::value, "");
	static_assert(hamon::is_same<vector3, decltype(v.xxx())>::value, "");
	static_assert(hamon::is_same<vector3, decltype(v.xyz())>::value, "");
	static_assert(hamon::is_same<vector2, decltype(v.xx())>::value, "");
	static_assert(hamon::is_same<vector2, decltype(v.ww())>::value, "");

	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 1, 1), v.xxxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 1, 2), v.xxxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 1, 3), v.xxxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 1, 4), v.xxxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 2, 1), v.xxyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 2, 2), v.xxyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 2, 3), v.xxyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 2, 4), v.xxyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 3, 1), v.xxzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 3, 2), v.xxzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 3, 3), v.xxzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 3, 4), v.xxzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 4, 1), v.xxwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 4, 2), v.xxwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 4, 3), v.xxwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 4, 4), v.xxww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 1, 1), v.xyxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 1, 2), v.xyxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 1, 3), v.xyxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 1, 4), v.xyxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 2, 1), v.xyyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 2, 2), v.xyyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 2, 3), v.xyyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 2, 4), v.xyyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 3, 1), v.xyzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 3, 2), v.xyzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 3, 3), v.xyzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 3, 4), v.xyzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 4, 1), v.xywx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 4, 2), v.xywy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 4, 3), v.xywz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 4, 4), v.xyww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 1, 1), v.xzxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 1, 2), v.xzxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 1, 3), v.xzxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 1, 4), v.xzxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 2, 1), v.xzyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 2, 2), v.xzyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 2, 3), v.xzyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 2, 4), v.xzyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 3, 1), v.xzzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 3, 2), v.xzzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 3, 3), v.xzzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 3, 4), v.xzzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 4, 1), v.xzwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 4, 2), v.xzwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 4, 3), v.xzwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 4, 4), v.xzww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 1, 1), v.xwxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 1, 2), v.xwxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 1, 3), v.xwxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 1, 4), v.xwxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 2, 1), v.xwyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 2, 2), v.xwyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 2, 3), v.xwyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 2, 4), v.xwyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 3, 1), v.xwzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 3, 2), v.xwzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 3, 3), v.xwzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 3, 4), v.xwzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 4, 1), v.xwwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 4, 2), v.xwwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 4, 3), v.xwwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 4, 4), v.xwww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 1, 1), v.yxxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 1, 2), v.yxxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 1, 3), v.yxxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 1, 4), v.yxxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 2, 1), v.yxyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 2, 2), v.yxyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 2, 3), v.yxyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 2, 4), v.yxyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 3, 1), v.yxzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 3, 2), v.yxzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 3, 3), v.yxzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 3, 4), v.yxzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 4, 1), v.yxwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 4, 2), v.yxwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 4, 3), v.yxwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 4, 4), v.yxww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 1, 1), v.yyxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 1, 2), v.yyxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 1, 3), v.yyxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 1, 4), v.yyxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 2, 1), v.yyyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 2, 2), v.yyyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 2, 3), v.yyyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 2, 4), v.yyyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 3, 1), v.yyzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 3, 2), v.yyzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 3, 3), v.yyzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 3, 4), v.yyzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 4, 1), v.yywx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 4, 2), v.yywy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 4, 3), v.yywz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 4, 4), v.yyww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 1, 1), v.yzxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 1, 2), v.yzxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 1, 3), v.yzxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 1, 4), v.yzxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 2, 1), v.yzyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 2, 2), v.yzyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 2, 3), v.yzyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 2, 4), v.yzyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 3, 1), v.yzzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 3, 2), v.yzzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 3, 3), v.yzzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 3, 4), v.yzzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 4, 1), v.yzwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 4, 2), v.yzwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 4, 3), v.yzwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 4, 4), v.yzww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 1, 1), v.ywxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 1, 2), v.ywxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 1, 3), v.ywxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 1, 4), v.ywxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 2, 1), v.ywyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 2, 2), v.ywyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 2, 3), v.ywyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 2, 4), v.ywyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 3, 1), v.ywzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 3, 2), v.ywzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 3, 3), v.ywzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 3, 4), v.ywzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 4, 1), v.ywwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 4, 2), v.ywwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 4, 3), v.ywwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 4, 4), v.ywww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 1, 1), v.zxxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 1, 2), v.zxxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 1, 3), v.zxxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 1, 4), v.zxxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 2, 1), v.zxyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 2, 2), v.zxyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 2, 3), v.zxyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 2, 4), v.zxyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 3, 1), v.zxzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 3, 2), v.zxzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 3, 3), v.zxzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 3, 4), v.zxzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 4, 1), v.zxwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 4, 2), v.zxwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 4, 3), v.zxwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 4, 4), v.zxww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 1, 1), v.zyxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 1, 2), v.zyxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 1, 3), v.zyxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 1, 4), v.zyxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 2, 1), v.zyyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 2, 2), v.zyyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 2, 3), v.zyyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 2, 4), v.zyyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 3, 1), v.zyzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 3, 2), v.zyzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 3, 3), v.zyzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 3, 4), v.zyzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 4, 1), v.zywx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 4, 2), v.zywy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 4, 3), v.zywz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 4, 4), v.zyww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 1, 1), v.zzxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 1, 2), v.zzxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 1, 3), v.zzxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 1, 4), v.zzxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 2, 1), v.zzyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 2, 2), v.zzyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 2, 3), v.zzyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 2, 4), v.zzyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 3, 1), v.zzzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 3, 2), v.zzzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 3, 3), v.zzzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 3, 4), v.zzzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 4, 1), v.zzwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 4, 2), v.zzwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 4, 3), v.zzwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 4, 4), v.zzww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 1, 1), v.zwxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 1, 2), v.zwxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 1, 3), v.zwxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 1, 4), v.zwxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 2, 1), v.zwyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 2, 2), v.zwyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 2, 3), v.zwyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 2, 4), v.zwyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 3, 1), v.zwzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 3, 2), v.zwzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 3, 3), v.zwzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 3, 4), v.zwzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 4, 1), v.zwwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 4, 2), v.zwwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 4, 3), v.zwwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 4, 4), v.zwww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 1, 1), v.wxxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 1, 2), v.wxxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 1, 3), v.wxxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 1, 4), v.wxxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 2, 1), v.wxyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 2, 2), v.wxyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 2, 3), v.wxyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 2, 4), v.wxyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 3, 1), v.wxzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 3, 2), v.wxzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 3, 3), v.wxzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 3, 4), v.wxzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 4, 1), v.wxwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 4, 2), v.wxwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 4, 3), v.wxwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 4, 4), v.wxww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 1, 1), v.wyxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 1, 2), v.wyxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 1, 3), v.wyxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 1, 4), v.wyxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 2, 1), v.wyyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 2, 2), v.wyyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 2, 3), v.wyyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 2, 4), v.wyyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 3, 1), v.wyzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 3, 2), v.wyzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 3, 3), v.wyzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 3, 4), v.wyzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 4, 1), v.wywx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 4, 2), v.wywy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 4, 3), v.wywz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 4, 4), v.wyww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 1, 1), v.wzxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 1, 2), v.wzxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 1, 3), v.wzxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 1, 4), v.wzxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 2, 1), v.wzyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 2, 2), v.wzyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 2, 3), v.wzyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 2, 4), v.wzyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 3, 1), v.wzzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 3, 2), v.wzzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 3, 3), v.wzzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 3, 4), v.wzzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 4, 1), v.wzwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 4, 2), v.wzwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 4, 3), v.wzwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 4, 4), v.wzww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 1, 1), v.wwxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 1, 2), v.wwxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 1, 3), v.wwxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 1, 4), v.wwxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 2, 1), v.wwyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 2, 2), v.wwyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 2, 3), v.wwyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 2, 4), v.wwyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 3, 1), v.wwzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 3, 2), v.wwzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 3, 3), v.wwzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 3, 4), v.wwzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 4, 1), v.wwwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 4, 2), v.wwwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 4, 3), v.wwwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 4, 4), v.wwww());

	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 1, 1), v.xxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 1, 2), v.xxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 1, 3), v.xxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 1, 4), v.xxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 2, 1), v.xyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 2, 2), v.xyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 2, 3), v.xyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 2, 4), v.xyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 3, 1), v.xzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 3, 2), v.xzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 3, 3), v.xzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 3, 4), v.xzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 4, 1), v.xwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 4, 2), v.xwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 4, 3), v.xwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 4, 4), v.xww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 1, 1), v.yxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 1, 2), v.yxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 1, 3), v.yxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 1, 4), v.yxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 2, 1), v.yyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 2, 2), v.yyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 2, 3), v.yyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 2, 4), v.yyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 3, 1), v.yzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 3, 2), v.yzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 3, 3), v.yzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 3, 4), v.yzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 4, 1), v.ywx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 4, 2), v.ywy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 4, 3), v.ywz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 4, 4), v.yww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 1, 1), v.zxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 1, 2), v.zxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 1, 3), v.zxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 1, 4), v.zxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 2, 1), v.zyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 2, 2), v.zyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 2, 3), v.zyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 2, 4), v.zyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 3, 1), v.zzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 3, 2), v.zzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 3, 3), v.zzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 3, 4), v.zzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 4, 1), v.zwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 4, 2), v.zwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 4, 3), v.zwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 4, 4), v.zww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 1, 1), v.wxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 1, 2), v.wxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 1, 3), v.wxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 1, 4), v.wxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 2, 1), v.wyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 2, 2), v.wyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 2, 3), v.wyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 2, 4), v.wyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 3, 1), v.wzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 3, 2), v.wzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 3, 3), v.wzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 3, 4), v.wzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 4, 1), v.wwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 4, 2), v.wwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 4, 3), v.wwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 4, 4), v.www());

	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(1, 1), v.xx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(1, 2), v.xy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(1, 3), v.xz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(1, 4), v.xw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(2, 1), v.yx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(2, 2), v.yy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(2, 3), v.yz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(2, 4), v.yw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(3, 1), v.zx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(3, 2), v.zy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(3, 3), v.zz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(3, 4), v.zw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(4, 1), v.wx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(4, 2), v.wy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(4, 3), v.wz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(4, 4), v.ww());
}

TYPED_TEST(VectorTest, SwizzleTest)
{
	using T = TypeParam;
	Vector2SwizzleTest<T>();
	Vector3SwizzleTest<T>();
	Vector4SwizzleTest<T>();
}

}	// namespace vector_test

}	// namespace hamon_qvm_test
