/**
 *	@file	elem.hpp
 *
 *	@brief
 */

#ifndef HAMON_PREPROCESSOR_SEQ_ELEM_HPP
#define HAMON_PREPROCESSOR_SEQ_ELEM_HPP
#
# include <hamon/preprocessor/cat.hpp>
# include <hamon/preprocessor/config/config.hpp>
# include <hamon/preprocessor/facilities/empty.hpp>
#
# /* HAMON_PP_SEQ_ELEM */
#
# if ~HAMON_PP_CONFIG_FLAGS() & HAMON_PP_CONFIG_MWCC()
#    define HAMON_PP_SEQ_ELEM(i, seq) HAMON_PP_SEQ_ELEM_I(i, seq)
# else
#    define HAMON_PP_SEQ_ELEM(i, seq) HAMON_PP_SEQ_ELEM_I((i, seq))
# endif
#
# if HAMON_PP_CONFIG_FLAGS() & HAMON_PP_CONFIG_MSVC()
#    define HAMON_PP_SEQ_ELEM_I(i, seq) HAMON_PP_SEQ_ELEM_II((HAMON_PP_SEQ_ELEM_ ## i seq))
#    define HAMON_PP_SEQ_ELEM_II(res) HAMON_PP_SEQ_ELEM_IV(HAMON_PP_SEQ_ELEM_III res)
#    define HAMON_PP_SEQ_ELEM_III(x, _) x HAMON_PP_EMPTY()
#    define HAMON_PP_SEQ_ELEM_IV(x) x
# elif HAMON_PP_CONFIG_FLAGS() & HAMON_PP_CONFIG_MWCC()
#    define HAMON_PP_SEQ_ELEM_I(par) HAMON_PP_SEQ_ELEM_II ## par
#    define HAMON_PP_SEQ_ELEM_II(i, seq) HAMON_PP_SEQ_ELEM_III(HAMON_PP_SEQ_ELEM_ ## i ## seq)
#    define HAMON_PP_SEQ_ELEM_III(im) HAMON_PP_SEQ_ELEM_IV(im)
#    define HAMON_PP_SEQ_ELEM_IV(x, _) x
# else
#    if defined(__IBMC__) || defined(__IBMCPP__)
#        define HAMON_PP_SEQ_ELEM_I(i, seq) HAMON_PP_SEQ_ELEM_II(HAMON_PP_CAT(HAMON_PP_SEQ_ELEM_ ## i, seq))
#    else
#        define HAMON_PP_SEQ_ELEM_I(i, seq) HAMON_PP_SEQ_ELEM_II(HAMON_PP_SEQ_ELEM_ ## i seq)
#    endif
#    define HAMON_PP_SEQ_ELEM_II(im) HAMON_PP_SEQ_ELEM_III(im)
#    define HAMON_PP_SEQ_ELEM_III(x, _) x
# endif
#
# define HAMON_PP_SEQ_ELEM_0(x) x, HAMON_PP_NIL
# define HAMON_PP_SEQ_ELEM_1(_) HAMON_PP_SEQ_ELEM_0
# define HAMON_PP_SEQ_ELEM_2(_) HAMON_PP_SEQ_ELEM_1
# define HAMON_PP_SEQ_ELEM_3(_) HAMON_PP_SEQ_ELEM_2
# define HAMON_PP_SEQ_ELEM_4(_) HAMON_PP_SEQ_ELEM_3
# define HAMON_PP_SEQ_ELEM_5(_) HAMON_PP_SEQ_ELEM_4
# define HAMON_PP_SEQ_ELEM_6(_) HAMON_PP_SEQ_ELEM_5
# define HAMON_PP_SEQ_ELEM_7(_) HAMON_PP_SEQ_ELEM_6
# define HAMON_PP_SEQ_ELEM_8(_) HAMON_PP_SEQ_ELEM_7
# define HAMON_PP_SEQ_ELEM_9(_) HAMON_PP_SEQ_ELEM_8
# define HAMON_PP_SEQ_ELEM_10(_) HAMON_PP_SEQ_ELEM_9
# define HAMON_PP_SEQ_ELEM_11(_) HAMON_PP_SEQ_ELEM_10
# define HAMON_PP_SEQ_ELEM_12(_) HAMON_PP_SEQ_ELEM_11
# define HAMON_PP_SEQ_ELEM_13(_) HAMON_PP_SEQ_ELEM_12
# define HAMON_PP_SEQ_ELEM_14(_) HAMON_PP_SEQ_ELEM_13
# define HAMON_PP_SEQ_ELEM_15(_) HAMON_PP_SEQ_ELEM_14
# define HAMON_PP_SEQ_ELEM_16(_) HAMON_PP_SEQ_ELEM_15
# define HAMON_PP_SEQ_ELEM_17(_) HAMON_PP_SEQ_ELEM_16
# define HAMON_PP_SEQ_ELEM_18(_) HAMON_PP_SEQ_ELEM_17
# define HAMON_PP_SEQ_ELEM_19(_) HAMON_PP_SEQ_ELEM_18
# define HAMON_PP_SEQ_ELEM_20(_) HAMON_PP_SEQ_ELEM_19
# define HAMON_PP_SEQ_ELEM_21(_) HAMON_PP_SEQ_ELEM_20
# define HAMON_PP_SEQ_ELEM_22(_) HAMON_PP_SEQ_ELEM_21
# define HAMON_PP_SEQ_ELEM_23(_) HAMON_PP_SEQ_ELEM_22
# define HAMON_PP_SEQ_ELEM_24(_) HAMON_PP_SEQ_ELEM_23
# define HAMON_PP_SEQ_ELEM_25(_) HAMON_PP_SEQ_ELEM_24
# define HAMON_PP_SEQ_ELEM_26(_) HAMON_PP_SEQ_ELEM_25
# define HAMON_PP_SEQ_ELEM_27(_) HAMON_PP_SEQ_ELEM_26
# define HAMON_PP_SEQ_ELEM_28(_) HAMON_PP_SEQ_ELEM_27
# define HAMON_PP_SEQ_ELEM_29(_) HAMON_PP_SEQ_ELEM_28
# define HAMON_PP_SEQ_ELEM_30(_) HAMON_PP_SEQ_ELEM_29
# define HAMON_PP_SEQ_ELEM_31(_) HAMON_PP_SEQ_ELEM_30
# define HAMON_PP_SEQ_ELEM_32(_) HAMON_PP_SEQ_ELEM_31
# define HAMON_PP_SEQ_ELEM_33(_) HAMON_PP_SEQ_ELEM_32
# define HAMON_PP_SEQ_ELEM_34(_) HAMON_PP_SEQ_ELEM_33
# define HAMON_PP_SEQ_ELEM_35(_) HAMON_PP_SEQ_ELEM_34
# define HAMON_PP_SEQ_ELEM_36(_) HAMON_PP_SEQ_ELEM_35
# define HAMON_PP_SEQ_ELEM_37(_) HAMON_PP_SEQ_ELEM_36
# define HAMON_PP_SEQ_ELEM_38(_) HAMON_PP_SEQ_ELEM_37
# define HAMON_PP_SEQ_ELEM_39(_) HAMON_PP_SEQ_ELEM_38
# define HAMON_PP_SEQ_ELEM_40(_) HAMON_PP_SEQ_ELEM_39
# define HAMON_PP_SEQ_ELEM_41(_) HAMON_PP_SEQ_ELEM_40
# define HAMON_PP_SEQ_ELEM_42(_) HAMON_PP_SEQ_ELEM_41
# define HAMON_PP_SEQ_ELEM_43(_) HAMON_PP_SEQ_ELEM_42
# define HAMON_PP_SEQ_ELEM_44(_) HAMON_PP_SEQ_ELEM_43
# define HAMON_PP_SEQ_ELEM_45(_) HAMON_PP_SEQ_ELEM_44
# define HAMON_PP_SEQ_ELEM_46(_) HAMON_PP_SEQ_ELEM_45
# define HAMON_PP_SEQ_ELEM_47(_) HAMON_PP_SEQ_ELEM_46
# define HAMON_PP_SEQ_ELEM_48(_) HAMON_PP_SEQ_ELEM_47
# define HAMON_PP_SEQ_ELEM_49(_) HAMON_PP_SEQ_ELEM_48
# define HAMON_PP_SEQ_ELEM_50(_) HAMON_PP_SEQ_ELEM_49
# define HAMON_PP_SEQ_ELEM_51(_) HAMON_PP_SEQ_ELEM_50
# define HAMON_PP_SEQ_ELEM_52(_) HAMON_PP_SEQ_ELEM_51
# define HAMON_PP_SEQ_ELEM_53(_) HAMON_PP_SEQ_ELEM_52
# define HAMON_PP_SEQ_ELEM_54(_) HAMON_PP_SEQ_ELEM_53
# define HAMON_PP_SEQ_ELEM_55(_) HAMON_PP_SEQ_ELEM_54
# define HAMON_PP_SEQ_ELEM_56(_) HAMON_PP_SEQ_ELEM_55
# define HAMON_PP_SEQ_ELEM_57(_) HAMON_PP_SEQ_ELEM_56
# define HAMON_PP_SEQ_ELEM_58(_) HAMON_PP_SEQ_ELEM_57
# define HAMON_PP_SEQ_ELEM_59(_) HAMON_PP_SEQ_ELEM_58
# define HAMON_PP_SEQ_ELEM_60(_) HAMON_PP_SEQ_ELEM_59
# define HAMON_PP_SEQ_ELEM_61(_) HAMON_PP_SEQ_ELEM_60
# define HAMON_PP_SEQ_ELEM_62(_) HAMON_PP_SEQ_ELEM_61
# define HAMON_PP_SEQ_ELEM_63(_) HAMON_PP_SEQ_ELEM_62
# define HAMON_PP_SEQ_ELEM_64(_) HAMON_PP_SEQ_ELEM_63
# define HAMON_PP_SEQ_ELEM_65(_) HAMON_PP_SEQ_ELEM_64
# define HAMON_PP_SEQ_ELEM_66(_) HAMON_PP_SEQ_ELEM_65
# define HAMON_PP_SEQ_ELEM_67(_) HAMON_PP_SEQ_ELEM_66
# define HAMON_PP_SEQ_ELEM_68(_) HAMON_PP_SEQ_ELEM_67
# define HAMON_PP_SEQ_ELEM_69(_) HAMON_PP_SEQ_ELEM_68
# define HAMON_PP_SEQ_ELEM_70(_) HAMON_PP_SEQ_ELEM_69
# define HAMON_PP_SEQ_ELEM_71(_) HAMON_PP_SEQ_ELEM_70
# define HAMON_PP_SEQ_ELEM_72(_) HAMON_PP_SEQ_ELEM_71
# define HAMON_PP_SEQ_ELEM_73(_) HAMON_PP_SEQ_ELEM_72
# define HAMON_PP_SEQ_ELEM_74(_) HAMON_PP_SEQ_ELEM_73
# define HAMON_PP_SEQ_ELEM_75(_) HAMON_PP_SEQ_ELEM_74
# define HAMON_PP_SEQ_ELEM_76(_) HAMON_PP_SEQ_ELEM_75
# define HAMON_PP_SEQ_ELEM_77(_) HAMON_PP_SEQ_ELEM_76
# define HAMON_PP_SEQ_ELEM_78(_) HAMON_PP_SEQ_ELEM_77
# define HAMON_PP_SEQ_ELEM_79(_) HAMON_PP_SEQ_ELEM_78
# define HAMON_PP_SEQ_ELEM_80(_) HAMON_PP_SEQ_ELEM_79
# define HAMON_PP_SEQ_ELEM_81(_) HAMON_PP_SEQ_ELEM_80
# define HAMON_PP_SEQ_ELEM_82(_) HAMON_PP_SEQ_ELEM_81
# define HAMON_PP_SEQ_ELEM_83(_) HAMON_PP_SEQ_ELEM_82
# define HAMON_PP_SEQ_ELEM_84(_) HAMON_PP_SEQ_ELEM_83
# define HAMON_PP_SEQ_ELEM_85(_) HAMON_PP_SEQ_ELEM_84
# define HAMON_PP_SEQ_ELEM_86(_) HAMON_PP_SEQ_ELEM_85
# define HAMON_PP_SEQ_ELEM_87(_) HAMON_PP_SEQ_ELEM_86
# define HAMON_PP_SEQ_ELEM_88(_) HAMON_PP_SEQ_ELEM_87
# define HAMON_PP_SEQ_ELEM_89(_) HAMON_PP_SEQ_ELEM_88
# define HAMON_PP_SEQ_ELEM_90(_) HAMON_PP_SEQ_ELEM_89
# define HAMON_PP_SEQ_ELEM_91(_) HAMON_PP_SEQ_ELEM_90
# define HAMON_PP_SEQ_ELEM_92(_) HAMON_PP_SEQ_ELEM_91
# define HAMON_PP_SEQ_ELEM_93(_) HAMON_PP_SEQ_ELEM_92
# define HAMON_PP_SEQ_ELEM_94(_) HAMON_PP_SEQ_ELEM_93
# define HAMON_PP_SEQ_ELEM_95(_) HAMON_PP_SEQ_ELEM_94
# define HAMON_PP_SEQ_ELEM_96(_) HAMON_PP_SEQ_ELEM_95
# define HAMON_PP_SEQ_ELEM_97(_) HAMON_PP_SEQ_ELEM_96
# define HAMON_PP_SEQ_ELEM_98(_) HAMON_PP_SEQ_ELEM_97
# define HAMON_PP_SEQ_ELEM_99(_) HAMON_PP_SEQ_ELEM_98
# define HAMON_PP_SEQ_ELEM_100(_) HAMON_PP_SEQ_ELEM_99
# define HAMON_PP_SEQ_ELEM_101(_) HAMON_PP_SEQ_ELEM_100
# define HAMON_PP_SEQ_ELEM_102(_) HAMON_PP_SEQ_ELEM_101
# define HAMON_PP_SEQ_ELEM_103(_) HAMON_PP_SEQ_ELEM_102
# define HAMON_PP_SEQ_ELEM_104(_) HAMON_PP_SEQ_ELEM_103
# define HAMON_PP_SEQ_ELEM_105(_) HAMON_PP_SEQ_ELEM_104
# define HAMON_PP_SEQ_ELEM_106(_) HAMON_PP_SEQ_ELEM_105
# define HAMON_PP_SEQ_ELEM_107(_) HAMON_PP_SEQ_ELEM_106
# define HAMON_PP_SEQ_ELEM_108(_) HAMON_PP_SEQ_ELEM_107
# define HAMON_PP_SEQ_ELEM_109(_) HAMON_PP_SEQ_ELEM_108
# define HAMON_PP_SEQ_ELEM_110(_) HAMON_PP_SEQ_ELEM_109
# define HAMON_PP_SEQ_ELEM_111(_) HAMON_PP_SEQ_ELEM_110
# define HAMON_PP_SEQ_ELEM_112(_) HAMON_PP_SEQ_ELEM_111
# define HAMON_PP_SEQ_ELEM_113(_) HAMON_PP_SEQ_ELEM_112
# define HAMON_PP_SEQ_ELEM_114(_) HAMON_PP_SEQ_ELEM_113
# define HAMON_PP_SEQ_ELEM_115(_) HAMON_PP_SEQ_ELEM_114
# define HAMON_PP_SEQ_ELEM_116(_) HAMON_PP_SEQ_ELEM_115
# define HAMON_PP_SEQ_ELEM_117(_) HAMON_PP_SEQ_ELEM_116
# define HAMON_PP_SEQ_ELEM_118(_) HAMON_PP_SEQ_ELEM_117
# define HAMON_PP_SEQ_ELEM_119(_) HAMON_PP_SEQ_ELEM_118
# define HAMON_PP_SEQ_ELEM_120(_) HAMON_PP_SEQ_ELEM_119
# define HAMON_PP_SEQ_ELEM_121(_) HAMON_PP_SEQ_ELEM_120
# define HAMON_PP_SEQ_ELEM_122(_) HAMON_PP_SEQ_ELEM_121
# define HAMON_PP_SEQ_ELEM_123(_) HAMON_PP_SEQ_ELEM_122
# define HAMON_PP_SEQ_ELEM_124(_) HAMON_PP_SEQ_ELEM_123
# define HAMON_PP_SEQ_ELEM_125(_) HAMON_PP_SEQ_ELEM_124
# define HAMON_PP_SEQ_ELEM_126(_) HAMON_PP_SEQ_ELEM_125
# define HAMON_PP_SEQ_ELEM_127(_) HAMON_PP_SEQ_ELEM_126
# define HAMON_PP_SEQ_ELEM_128(_) HAMON_PP_SEQ_ELEM_127
# define HAMON_PP_SEQ_ELEM_129(_) HAMON_PP_SEQ_ELEM_128
# define HAMON_PP_SEQ_ELEM_130(_) HAMON_PP_SEQ_ELEM_129
# define HAMON_PP_SEQ_ELEM_131(_) HAMON_PP_SEQ_ELEM_130
# define HAMON_PP_SEQ_ELEM_132(_) HAMON_PP_SEQ_ELEM_131
# define HAMON_PP_SEQ_ELEM_133(_) HAMON_PP_SEQ_ELEM_132
# define HAMON_PP_SEQ_ELEM_134(_) HAMON_PP_SEQ_ELEM_133
# define HAMON_PP_SEQ_ELEM_135(_) HAMON_PP_SEQ_ELEM_134
# define HAMON_PP_SEQ_ELEM_136(_) HAMON_PP_SEQ_ELEM_135
# define HAMON_PP_SEQ_ELEM_137(_) HAMON_PP_SEQ_ELEM_136
# define HAMON_PP_SEQ_ELEM_138(_) HAMON_PP_SEQ_ELEM_137
# define HAMON_PP_SEQ_ELEM_139(_) HAMON_PP_SEQ_ELEM_138
# define HAMON_PP_SEQ_ELEM_140(_) HAMON_PP_SEQ_ELEM_139
# define HAMON_PP_SEQ_ELEM_141(_) HAMON_PP_SEQ_ELEM_140
# define HAMON_PP_SEQ_ELEM_142(_) HAMON_PP_SEQ_ELEM_141
# define HAMON_PP_SEQ_ELEM_143(_) HAMON_PP_SEQ_ELEM_142
# define HAMON_PP_SEQ_ELEM_144(_) HAMON_PP_SEQ_ELEM_143
# define HAMON_PP_SEQ_ELEM_145(_) HAMON_PP_SEQ_ELEM_144
# define HAMON_PP_SEQ_ELEM_146(_) HAMON_PP_SEQ_ELEM_145
# define HAMON_PP_SEQ_ELEM_147(_) HAMON_PP_SEQ_ELEM_146
# define HAMON_PP_SEQ_ELEM_148(_) HAMON_PP_SEQ_ELEM_147
# define HAMON_PP_SEQ_ELEM_149(_) HAMON_PP_SEQ_ELEM_148
# define HAMON_PP_SEQ_ELEM_150(_) HAMON_PP_SEQ_ELEM_149
# define HAMON_PP_SEQ_ELEM_151(_) HAMON_PP_SEQ_ELEM_150
# define HAMON_PP_SEQ_ELEM_152(_) HAMON_PP_SEQ_ELEM_151
# define HAMON_PP_SEQ_ELEM_153(_) HAMON_PP_SEQ_ELEM_152
# define HAMON_PP_SEQ_ELEM_154(_) HAMON_PP_SEQ_ELEM_153
# define HAMON_PP_SEQ_ELEM_155(_) HAMON_PP_SEQ_ELEM_154
# define HAMON_PP_SEQ_ELEM_156(_) HAMON_PP_SEQ_ELEM_155
# define HAMON_PP_SEQ_ELEM_157(_) HAMON_PP_SEQ_ELEM_156
# define HAMON_PP_SEQ_ELEM_158(_) HAMON_PP_SEQ_ELEM_157
# define HAMON_PP_SEQ_ELEM_159(_) HAMON_PP_SEQ_ELEM_158
# define HAMON_PP_SEQ_ELEM_160(_) HAMON_PP_SEQ_ELEM_159
# define HAMON_PP_SEQ_ELEM_161(_) HAMON_PP_SEQ_ELEM_160
# define HAMON_PP_SEQ_ELEM_162(_) HAMON_PP_SEQ_ELEM_161
# define HAMON_PP_SEQ_ELEM_163(_) HAMON_PP_SEQ_ELEM_162
# define HAMON_PP_SEQ_ELEM_164(_) HAMON_PP_SEQ_ELEM_163
# define HAMON_PP_SEQ_ELEM_165(_) HAMON_PP_SEQ_ELEM_164
# define HAMON_PP_SEQ_ELEM_166(_) HAMON_PP_SEQ_ELEM_165
# define HAMON_PP_SEQ_ELEM_167(_) HAMON_PP_SEQ_ELEM_166
# define HAMON_PP_SEQ_ELEM_168(_) HAMON_PP_SEQ_ELEM_167
# define HAMON_PP_SEQ_ELEM_169(_) HAMON_PP_SEQ_ELEM_168
# define HAMON_PP_SEQ_ELEM_170(_) HAMON_PP_SEQ_ELEM_169
# define HAMON_PP_SEQ_ELEM_171(_) HAMON_PP_SEQ_ELEM_170
# define HAMON_PP_SEQ_ELEM_172(_) HAMON_PP_SEQ_ELEM_171
# define HAMON_PP_SEQ_ELEM_173(_) HAMON_PP_SEQ_ELEM_172
# define HAMON_PP_SEQ_ELEM_174(_) HAMON_PP_SEQ_ELEM_173
# define HAMON_PP_SEQ_ELEM_175(_) HAMON_PP_SEQ_ELEM_174
# define HAMON_PP_SEQ_ELEM_176(_) HAMON_PP_SEQ_ELEM_175
# define HAMON_PP_SEQ_ELEM_177(_) HAMON_PP_SEQ_ELEM_176
# define HAMON_PP_SEQ_ELEM_178(_) HAMON_PP_SEQ_ELEM_177
# define HAMON_PP_SEQ_ELEM_179(_) HAMON_PP_SEQ_ELEM_178
# define HAMON_PP_SEQ_ELEM_180(_) HAMON_PP_SEQ_ELEM_179
# define HAMON_PP_SEQ_ELEM_181(_) HAMON_PP_SEQ_ELEM_180
# define HAMON_PP_SEQ_ELEM_182(_) HAMON_PP_SEQ_ELEM_181
# define HAMON_PP_SEQ_ELEM_183(_) HAMON_PP_SEQ_ELEM_182
# define HAMON_PP_SEQ_ELEM_184(_) HAMON_PP_SEQ_ELEM_183
# define HAMON_PP_SEQ_ELEM_185(_) HAMON_PP_SEQ_ELEM_184
# define HAMON_PP_SEQ_ELEM_186(_) HAMON_PP_SEQ_ELEM_185
# define HAMON_PP_SEQ_ELEM_187(_) HAMON_PP_SEQ_ELEM_186
# define HAMON_PP_SEQ_ELEM_188(_) HAMON_PP_SEQ_ELEM_187
# define HAMON_PP_SEQ_ELEM_189(_) HAMON_PP_SEQ_ELEM_188
# define HAMON_PP_SEQ_ELEM_190(_) HAMON_PP_SEQ_ELEM_189
# define HAMON_PP_SEQ_ELEM_191(_) HAMON_PP_SEQ_ELEM_190
# define HAMON_PP_SEQ_ELEM_192(_) HAMON_PP_SEQ_ELEM_191
# define HAMON_PP_SEQ_ELEM_193(_) HAMON_PP_SEQ_ELEM_192
# define HAMON_PP_SEQ_ELEM_194(_) HAMON_PP_SEQ_ELEM_193
# define HAMON_PP_SEQ_ELEM_195(_) HAMON_PP_SEQ_ELEM_194
# define HAMON_PP_SEQ_ELEM_196(_) HAMON_PP_SEQ_ELEM_195
# define HAMON_PP_SEQ_ELEM_197(_) HAMON_PP_SEQ_ELEM_196
# define HAMON_PP_SEQ_ELEM_198(_) HAMON_PP_SEQ_ELEM_197
# define HAMON_PP_SEQ_ELEM_199(_) HAMON_PP_SEQ_ELEM_198
# define HAMON_PP_SEQ_ELEM_200(_) HAMON_PP_SEQ_ELEM_199
# define HAMON_PP_SEQ_ELEM_201(_) HAMON_PP_SEQ_ELEM_200
# define HAMON_PP_SEQ_ELEM_202(_) HAMON_PP_SEQ_ELEM_201
# define HAMON_PP_SEQ_ELEM_203(_) HAMON_PP_SEQ_ELEM_202
# define HAMON_PP_SEQ_ELEM_204(_) HAMON_PP_SEQ_ELEM_203
# define HAMON_PP_SEQ_ELEM_205(_) HAMON_PP_SEQ_ELEM_204
# define HAMON_PP_SEQ_ELEM_206(_) HAMON_PP_SEQ_ELEM_205
# define HAMON_PP_SEQ_ELEM_207(_) HAMON_PP_SEQ_ELEM_206
# define HAMON_PP_SEQ_ELEM_208(_) HAMON_PP_SEQ_ELEM_207
# define HAMON_PP_SEQ_ELEM_209(_) HAMON_PP_SEQ_ELEM_208
# define HAMON_PP_SEQ_ELEM_210(_) HAMON_PP_SEQ_ELEM_209
# define HAMON_PP_SEQ_ELEM_211(_) HAMON_PP_SEQ_ELEM_210
# define HAMON_PP_SEQ_ELEM_212(_) HAMON_PP_SEQ_ELEM_211
# define HAMON_PP_SEQ_ELEM_213(_) HAMON_PP_SEQ_ELEM_212
# define HAMON_PP_SEQ_ELEM_214(_) HAMON_PP_SEQ_ELEM_213
# define HAMON_PP_SEQ_ELEM_215(_) HAMON_PP_SEQ_ELEM_214
# define HAMON_PP_SEQ_ELEM_216(_) HAMON_PP_SEQ_ELEM_215
# define HAMON_PP_SEQ_ELEM_217(_) HAMON_PP_SEQ_ELEM_216
# define HAMON_PP_SEQ_ELEM_218(_) HAMON_PP_SEQ_ELEM_217
# define HAMON_PP_SEQ_ELEM_219(_) HAMON_PP_SEQ_ELEM_218
# define HAMON_PP_SEQ_ELEM_220(_) HAMON_PP_SEQ_ELEM_219
# define HAMON_PP_SEQ_ELEM_221(_) HAMON_PP_SEQ_ELEM_220
# define HAMON_PP_SEQ_ELEM_222(_) HAMON_PP_SEQ_ELEM_221
# define HAMON_PP_SEQ_ELEM_223(_) HAMON_PP_SEQ_ELEM_222
# define HAMON_PP_SEQ_ELEM_224(_) HAMON_PP_SEQ_ELEM_223
# define HAMON_PP_SEQ_ELEM_225(_) HAMON_PP_SEQ_ELEM_224
# define HAMON_PP_SEQ_ELEM_226(_) HAMON_PP_SEQ_ELEM_225
# define HAMON_PP_SEQ_ELEM_227(_) HAMON_PP_SEQ_ELEM_226
# define HAMON_PP_SEQ_ELEM_228(_) HAMON_PP_SEQ_ELEM_227
# define HAMON_PP_SEQ_ELEM_229(_) HAMON_PP_SEQ_ELEM_228
# define HAMON_PP_SEQ_ELEM_230(_) HAMON_PP_SEQ_ELEM_229
# define HAMON_PP_SEQ_ELEM_231(_) HAMON_PP_SEQ_ELEM_230
# define HAMON_PP_SEQ_ELEM_232(_) HAMON_PP_SEQ_ELEM_231
# define HAMON_PP_SEQ_ELEM_233(_) HAMON_PP_SEQ_ELEM_232
# define HAMON_PP_SEQ_ELEM_234(_) HAMON_PP_SEQ_ELEM_233
# define HAMON_PP_SEQ_ELEM_235(_) HAMON_PP_SEQ_ELEM_234
# define HAMON_PP_SEQ_ELEM_236(_) HAMON_PP_SEQ_ELEM_235
# define HAMON_PP_SEQ_ELEM_237(_) HAMON_PP_SEQ_ELEM_236
# define HAMON_PP_SEQ_ELEM_238(_) HAMON_PP_SEQ_ELEM_237
# define HAMON_PP_SEQ_ELEM_239(_) HAMON_PP_SEQ_ELEM_238
# define HAMON_PP_SEQ_ELEM_240(_) HAMON_PP_SEQ_ELEM_239
# define HAMON_PP_SEQ_ELEM_241(_) HAMON_PP_SEQ_ELEM_240
# define HAMON_PP_SEQ_ELEM_242(_) HAMON_PP_SEQ_ELEM_241
# define HAMON_PP_SEQ_ELEM_243(_) HAMON_PP_SEQ_ELEM_242
# define HAMON_PP_SEQ_ELEM_244(_) HAMON_PP_SEQ_ELEM_243
# define HAMON_PP_SEQ_ELEM_245(_) HAMON_PP_SEQ_ELEM_244
# define HAMON_PP_SEQ_ELEM_246(_) HAMON_PP_SEQ_ELEM_245
# define HAMON_PP_SEQ_ELEM_247(_) HAMON_PP_SEQ_ELEM_246
# define HAMON_PP_SEQ_ELEM_248(_) HAMON_PP_SEQ_ELEM_247
# define HAMON_PP_SEQ_ELEM_249(_) HAMON_PP_SEQ_ELEM_248
# define HAMON_PP_SEQ_ELEM_250(_) HAMON_PP_SEQ_ELEM_249
# define HAMON_PP_SEQ_ELEM_251(_) HAMON_PP_SEQ_ELEM_250
# define HAMON_PP_SEQ_ELEM_252(_) HAMON_PP_SEQ_ELEM_251
# define HAMON_PP_SEQ_ELEM_253(_) HAMON_PP_SEQ_ELEM_252
# define HAMON_PP_SEQ_ELEM_254(_) HAMON_PP_SEQ_ELEM_253
# define HAMON_PP_SEQ_ELEM_255(_) HAMON_PP_SEQ_ELEM_254
#
#endif // HAMON_PREPROCESSOR_SEQ_ELEM_HPP
