/**
 *	@file	for_each_product.hpp
 *
 *	@brief
 */

#ifndef HAMON_PREPROCESSOR_SEQ_FOR_EACH_PRODUCT_HPP
#define HAMON_PREPROCESSOR_SEQ_FOR_EACH_PRODUCT_HPP
#
# include <hamon/preprocessor/arithmetic/dec.hpp>
# include <hamon/preprocessor/config/config.hpp>
# include <hamon/preprocessor/control/if.hpp>
# include <hamon/preprocessor/repetition/for.hpp>
# include <hamon/preprocessor/seq/seq.hpp>
# include <hamon/preprocessor/seq/size.hpp>
# include <hamon/preprocessor/tuple/elem.hpp>
# include <hamon/preprocessor/tuple/rem.hpp>
#
# /* HAMON_PP_SEQ_FOR_EACH_PRODUCT */
#
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT(macro, sets) HAMON_PP_SEQ_FOR_EACH_PRODUCT_E(HAMON_PP_FOR, macro, sets)
#
# /* HAMON_PP_SEQ_FOR_EACH_PRODUCT_R */
#
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_R(r, macro, sets) HAMON_PP_SEQ_FOR_EACH_PRODUCT_E(HAMON_PP_FOR_ ## r, macro, sets)
#
# if ~HAMON_PP_CONFIG_FLAGS() & HAMON_PP_CONFIG_EDG()
#    define HAMON_PP_SEQ_FOR_EACH_PRODUCT_E(impl, macro, sets) impl((HAMON_PP_SEQ_HEAD(sets)(nil), HAMON_PP_SEQ_TAIL(sets)(nil), (nil), macro), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_0)
# else
#    define HAMON_PP_SEQ_FOR_EACH_PRODUCT_E(impl, macro, sets) HAMON_PP_SEQ_FOR_EACH_PRODUCT_E_I(impl, macro, sets)
#    define HAMON_PP_SEQ_FOR_EACH_PRODUCT_E_I(impl, macro, sets) impl((HAMON_PP_SEQ_HEAD(sets)(nil), HAMON_PP_SEQ_TAIL(sets)(nil), (nil), macro), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_0)
# endif
#
# if HAMON_PP_CONFIG_FLAGS() & HAMON_PP_CONFIG_STRICT()
#    define HAMON_PP_SEQ_FOR_EACH_PRODUCT_P(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_P_I data
#    define HAMON_PP_SEQ_FOR_EACH_PRODUCT_P_I(cset, rset, res, macro) HAMON_PP_DEC(HAMON_PP_SEQ_SIZE(cset))
# else
#    define HAMON_PP_SEQ_FOR_EACH_PRODUCT_P(r, data) HAMON_PP_DEC(HAMON_PP_SEQ_SIZE(HAMON_PP_TUPLE_ELEM(4, 0, data)))
# endif
#
# if ~HAMON_PP_CONFIG_FLAGS() & HAMON_PP_CONFIG_MWCC()
#    define HAMON_PP_SEQ_FOR_EACH_PRODUCT_O(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_O_I data
#    define HAMON_PP_SEQ_FOR_EACH_PRODUCT_O_I(cset, rset, res, macro) (HAMON_PP_SEQ_TAIL(cset), rset, res, macro)
# else
#    define HAMON_PP_SEQ_FOR_EACH_PRODUCT_O(r, data) (HAMON_PP_SEQ_TAIL(HAMON_PP_TUPLE_ELEM(4, 0, data)), HAMON_PP_TUPLE_ELEM(4, 1, data), HAMON_PP_TUPLE_ELEM(4, 2, data), HAMON_PP_TUPLE_ELEM(4, 3, data))
# endif
#
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, i) HAMON_PP_IF(HAMON_PP_DEC(HAMON_PP_SEQ_SIZE(HAMON_PP_TUPLE_ELEM(4, 1, data))), HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_ ## i, HAMON_PP_SEQ_FOR_EACH_PRODUCT_I)
#
# if ~HAMON_PP_CONFIG_FLAGS() & HAMON_PP_CONFIG_EDG()
#    define HAMON_PP_SEQ_FOR_EACH_PRODUCT_I(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_I_I(r, HAMON_PP_TUPLE_ELEM(4, 0, data), HAMON_PP_TUPLE_ELEM(4, 1, data), HAMON_PP_TUPLE_ELEM(4, 2, data), HAMON_PP_TUPLE_ELEM(4, 3, data))
# else
#    define HAMON_PP_SEQ_FOR_EACH_PRODUCT_I(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_I_IM(r, HAMON_PP_TUPLE_REM_4 data)
#    define HAMON_PP_SEQ_FOR_EACH_PRODUCT_I_IM(r, im) HAMON_PP_SEQ_FOR_EACH_PRODUCT_I_I(r, im)
# endif
#
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_I_I(r, cset, rset, res, macro) macro(r, HAMON_PP_SEQ_TAIL(res (HAMON_PP_SEQ_HEAD(cset))))
#
# if ~HAMON_PP_CONFIG_FLAGS() & HAMON_PP_CONFIG_MWCC()
#    define HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_H_I data
# else
#    define HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_H_I(HAMON_PP_TUPLE_ELEM(4, 0, data), HAMON_PP_TUPLE_ELEM(4, 1, data), HAMON_PP_TUPLE_ELEM(4, 2, data), HAMON_PP_TUPLE_ELEM(4, 3, data))
# endif
#
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_H_I(cset, rset, res, macro) (HAMON_PP_SEQ_HEAD(rset)(nil), HAMON_PP_SEQ_TAIL(rset), res (HAMON_PP_SEQ_HEAD(cset)), macro)
#
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_0(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 0)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_1(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 1)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_2(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 2)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_3(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 3)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_4(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 4)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_5(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 5)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_6(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 6)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_7(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 7)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_8(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 8)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_9(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 9)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_10(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 10)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_11(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 11)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_12(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 12)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_13(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 13)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_14(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 14)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_15(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 15)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_16(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 16)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_17(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 17)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_18(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 18)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_19(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 19)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_20(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 20)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_21(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 21)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_22(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 22)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_23(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 23)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_24(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 24)(r, data)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_25(r, data) HAMON_PP_SEQ_FOR_EACH_PRODUCT_C(data, 25)(r, data)
#
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_0(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_1)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_1(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_2)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_2(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_3)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_3(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_4)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_4(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_5)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_5(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_6)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_6(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_7)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_7(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_8)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_8(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_9)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_9(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_10)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_10(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_11)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_11(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_12)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_12(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_13)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_13(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_14)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_14(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_15)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_15(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_16)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_16(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_17)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_17(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_18)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_18(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_19)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_19(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_20)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_20(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_21)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_21(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_22)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_22(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_23)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_23(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_24)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_24(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_25)
# define HAMON_PP_SEQ_FOR_EACH_PRODUCT_N_25(r, data) HAMON_PP_FOR_ ## r(HAMON_PP_SEQ_FOR_EACH_PRODUCT_H(data), HAMON_PP_SEQ_FOR_EACH_PRODUCT_P, HAMON_PP_SEQ_FOR_EACH_PRODUCT_O, HAMON_PP_SEQ_FOR_EACH_PRODUCT_M_26)
#
#endif // HAMON_PREPROCESSOR_SEQ_FOR_EACH_PRODUCT_HPP
