/**
 *	@file	ranges.hpp
 *
 *	@brief	Algorithm Ranges
 */

#ifndef HAMON_ALGORITHM_RANGES_HPP
#define HAMON_ALGORITHM_RANGES_HPP

#include <hamon/algorithm/ranges/adjacent_find.hpp>
#include <hamon/algorithm/ranges/all_of.hpp>
#include <hamon/algorithm/ranges/any_of.hpp>
#include <hamon/algorithm/ranges/binary_search.hpp>
#include <hamon/algorithm/ranges/clamp.hpp>
//#include <hamon/algorithm/ranges/contains.hpp>
#include <hamon/algorithm/ranges/copy.hpp>
#include <hamon/algorithm/ranges/copy_backward.hpp>
#include <hamon/algorithm/ranges/copy_if.hpp>
#include <hamon/algorithm/ranges/copy_n.hpp>
#include <hamon/algorithm/ranges/count.hpp>
#include <hamon/algorithm/ranges/count_if.hpp>
//#include <hamon/algorithm/ranges/ends_with.hpp>
#include <hamon/algorithm/ranges/equal.hpp>
#include <hamon/algorithm/ranges/equal_range.hpp>
#include <hamon/algorithm/ranges/fill.hpp>
#include <hamon/algorithm/ranges/fill_n.hpp>
#include <hamon/algorithm/ranges/find.hpp>
#include <hamon/algorithm/ranges/find_end.hpp>
#include <hamon/algorithm/ranges/find_first_of.hpp>
#include <hamon/algorithm/ranges/find_if.hpp>
#include <hamon/algorithm/ranges/find_if_not.hpp>
//#include <hamon/algorithm/ranges/find_last.hpp>
//#include <hamon/algorithm/ranges/find_last_if.hpp>
//#include <hamon/algorithm/ranges/find_last_if_not.hpp>
#include <hamon/algorithm/ranges/for_each.hpp>
#include <hamon/algorithm/ranges/for_each_n.hpp>
#include <hamon/algorithm/ranges/generate.hpp>
#include <hamon/algorithm/ranges/generate_n.hpp>
//#include <hamon/algorithm/ranges/includes.hpp>
//#include <hamon/algorithm/ranges/inplace_merge.hpp>
//#include <hamon/algorithm/ranges/in_found_result.hpp>
#include <hamon/algorithm/ranges/in_fun_result.hpp>
#include <hamon/algorithm/ranges/in_in_out_result.hpp>
#include <hamon/algorithm/ranges/in_in_result.hpp>
#include <hamon/algorithm/ranges/in_out_out_result.hpp>
#include <hamon/algorithm/ranges/in_out_result.hpp>
#include <hamon/algorithm/ranges/is_heap.hpp>
#include <hamon/algorithm/ranges/is_heap_until.hpp>
#include <hamon/algorithm/ranges/is_partitioned.hpp>
#include <hamon/algorithm/ranges/is_permutation.hpp>
#include <hamon/algorithm/ranges/is_sorted.hpp>
#include <hamon/algorithm/ranges/is_sorted_until.hpp>
#include <hamon/algorithm/ranges/lexicographical_compare.hpp>
#include <hamon/algorithm/ranges/lower_bound.hpp>
#include <hamon/algorithm/ranges/make_heap.hpp>
#include <hamon/algorithm/ranges/max.hpp>
#include <hamon/algorithm/ranges/max_element.hpp>
//#include <hamon/algorithm/ranges/merge.hpp>
#include <hamon/algorithm/ranges/min.hpp>
#include <hamon/algorithm/ranges/minmax.hpp>
#include <hamon/algorithm/ranges/minmax_element.hpp>
#include <hamon/algorithm/ranges/min_element.hpp>
#include <hamon/algorithm/ranges/min_max_result.hpp>
#include <hamon/algorithm/ranges/mismatch.hpp>
#include <hamon/algorithm/ranges/move.hpp>
#include <hamon/algorithm/ranges/move_backward.hpp>
#include <hamon/algorithm/ranges/next_permutation.hpp>
#include <hamon/algorithm/ranges/none_of.hpp>
//#include <hamon/algorithm/ranges/nth_element.hpp>
//#include <hamon/algorithm/ranges/partial_sort.hpp>
//#include <hamon/algorithm/ranges/partial_sort_copy.hpp>
#include <hamon/algorithm/ranges/partition.hpp>
#include <hamon/algorithm/ranges/partition_copy.hpp>
#include <hamon/algorithm/ranges/partition_point.hpp>
#include <hamon/algorithm/ranges/pop_heap.hpp>
#include <hamon/algorithm/ranges/prev_permutation.hpp>
#include <hamon/algorithm/ranges/push_heap.hpp>
//#include <hamon/algorithm/ranges/radix_sort.hpp>
#include <hamon/algorithm/ranges/remove.hpp>
#include <hamon/algorithm/ranges/remove_copy.hpp>
#include <hamon/algorithm/ranges/remove_copy_if.hpp>
#include <hamon/algorithm/ranges/remove_if.hpp>
#include <hamon/algorithm/ranges/replace.hpp>
#include <hamon/algorithm/ranges/replace_copy.hpp>
#include <hamon/algorithm/ranges/replace_copy_if.hpp>
#include <hamon/algorithm/ranges/replace_if.hpp>
#include <hamon/algorithm/ranges/reverse.hpp>
#include <hamon/algorithm/ranges/reverse_copy.hpp>
#include <hamon/algorithm/ranges/rotate.hpp>
#include <hamon/algorithm/ranges/rotate_copy.hpp>
//#include <hamon/algorithm/ranges/sample.hpp>
#include <hamon/algorithm/ranges/search.hpp>
#include <hamon/algorithm/ranges/search_n.hpp>
//#include <hamon/algorithm/ranges/set_difference.hpp>
//#include <hamon/algorithm/ranges/set_intersection.hpp>
//#include <hamon/algorithm/ranges/set_symmetric_difference.hpp>
//#include <hamon/algorithm/ranges/set_union.hpp>
#include <hamon/algorithm/ranges/shuffle.hpp>
//#include <hamon/algorithm/ranges/sort.hpp>
#include <hamon/algorithm/ranges/sort_heap.hpp>
#include <hamon/algorithm/ranges/stable_partition.hpp>
//#include <hamon/algorithm/ranges/stable_sort.hpp>
//#include <hamon/algorithm/ranges/starts_with.hpp>
#include <hamon/algorithm/ranges/swap_ranges.hpp>
#include <hamon/algorithm/ranges/transform.hpp>
#include <hamon/algorithm/ranges/unique.hpp>
#include <hamon/algorithm/ranges/unique_copy.hpp>
#include <hamon/algorithm/ranges/upper_bound.hpp>

#endif // HAMON_ALGORITHM_RANGES_HPP
