/**
 *	@file	wavenumber.hpp
 *
 *	@brief	wavenumber の定義
 */

#ifndef HAMON_UNITS_WAVENUMBER_HPP
#define HAMON_UNITS_WAVENUMBER_HPP

#include <hamon/units/length.hpp>

namespace hamon
{

namespace units
{

#define HAMON_UNITS_DECLARE_WAVENUMBER(Length)	\
	template <typename T> using reciprocal_ ## Length  = decltype(T() / Length<T>())

#define HAMON_UNITS_DECLARE_WAVENUMBER_SI_PREFIX(Name) \
	HAMON_UNITS_DECLARE_WAVENUMBER(atto  ## Name);     \
	HAMON_UNITS_DECLARE_WAVENUMBER(femto ## Name);     \
	HAMON_UNITS_DECLARE_WAVENUMBER(pico  ## Name);     \
	HAMON_UNITS_DECLARE_WAVENUMBER(nano  ## Name);     \
	HAMON_UNITS_DECLARE_WAVENUMBER(micro ## Name);     \
	HAMON_UNITS_DECLARE_WAVENUMBER(milli ## Name);     \
	HAMON_UNITS_DECLARE_WAVENUMBER(centi ## Name);     \
	HAMON_UNITS_DECLARE_WAVENUMBER(deci  ## Name);     \
	HAMON_UNITS_DECLARE_WAVENUMBER(Name);              \
	HAMON_UNITS_DECLARE_WAVENUMBER(deca  ## Name);     \
	HAMON_UNITS_DECLARE_WAVENUMBER(hecto ## Name);     \
	HAMON_UNITS_DECLARE_WAVENUMBER(kilo  ## Name);     \
	HAMON_UNITS_DECLARE_WAVENUMBER(mega  ## Name);     \
	HAMON_UNITS_DECLARE_WAVENUMBER(giga  ## Name);     \
	HAMON_UNITS_DECLARE_WAVENUMBER(tera  ## Name);     \
	HAMON_UNITS_DECLARE_WAVENUMBER(peta  ## Name);     \
	HAMON_UNITS_DECLARE_WAVENUMBER(exa   ## Name)

// 毎メートル
HAMON_UNITS_DECLARE_WAVENUMBER_SI_PREFIX(metre);
HAMON_UNITS_DECLARE_WAVENUMBER_SI_PREFIX(metres);
HAMON_UNITS_DECLARE_WAVENUMBER_SI_PREFIX(meter);
HAMON_UNITS_DECLARE_WAVENUMBER_SI_PREFIX(meters);

HAMON_UNITS_DECLARE_WAVENUMBER(inch);
HAMON_UNITS_DECLARE_WAVENUMBER(inches);
HAMON_UNITS_DECLARE_WAVENUMBER(foot);
HAMON_UNITS_DECLARE_WAVENUMBER(feet);
HAMON_UNITS_DECLARE_WAVENUMBER(yard);
HAMON_UNITS_DECLARE_WAVENUMBER(yards);
HAMON_UNITS_DECLARE_WAVENUMBER(chain);
HAMON_UNITS_DECLARE_WAVENUMBER(chains);
HAMON_UNITS_DECLARE_WAVENUMBER(furlong);
HAMON_UNITS_DECLARE_WAVENUMBER(furlongs);
HAMON_UNITS_DECLARE_WAVENUMBER(mile);
HAMON_UNITS_DECLARE_WAVENUMBER(miles);

#undef HAMON_UNITS_DECLARE_WAVENUMBER
#undef HAMON_UNITS_DECLARE_WAVENUMBER_SI_PREFIX

}	// namespace units

}	// namespace hamon

#include <hamon/units/kayser.hpp>

#endif // HAMON_UNITS_WAVENUMBER_HPP
