/**
 *	@file	algorithm.hpp
 *
 *	@brief	Algorithm library
 */

#ifndef HAMON_ALGORITHM_HPP
#define HAMON_ALGORITHM_HPP

#include <hamon/algorithm/adjacent_find.hpp>
#include <hamon/algorithm/all_of.hpp>
#include <hamon/algorithm/any_of.hpp>
#include <hamon/algorithm/binary_search.hpp>
#include <hamon/algorithm/clamp.hpp>
#include <hamon/algorithm/config.hpp>
#include <hamon/algorithm/contains.hpp>
#include <hamon/algorithm/copy.hpp>
#include <hamon/algorithm/copy_backward.hpp>
#include <hamon/algorithm/copy_if.hpp>
#include <hamon/algorithm/copy_n.hpp>
#include <hamon/algorithm/count.hpp>
#include <hamon/algorithm/count_if.hpp>
#include <hamon/algorithm/equal.hpp>
#include <hamon/algorithm/equal_range.hpp>
#include <hamon/algorithm/fill.hpp>
#include <hamon/algorithm/fill_n.hpp>
#include <hamon/algorithm/find.hpp>
#include <hamon/algorithm/find_end.hpp>
#include <hamon/algorithm/find_first_of.hpp>
#include <hamon/algorithm/find_if.hpp>
#include <hamon/algorithm/find_if_not.hpp>
#include <hamon/algorithm/for_each.hpp>
#include <hamon/algorithm/for_each_n.hpp>
#include <hamon/algorithm/generate.hpp>
#include <hamon/algorithm/generate_n.hpp>
#include <hamon/algorithm/includes.hpp>
//#include <hamon/algorithm/inplace_merge.hpp>
#include <hamon/algorithm/is_heap.hpp>
#include <hamon/algorithm/is_heap_until.hpp>
//#include <hamon/algorithm/is_partitioned.hpp>
//#include <hamon/algorithm/is_permutation.hpp>
#include <hamon/algorithm/is_sorted.hpp>
#include <hamon/algorithm/is_sorted_until.hpp>
#include <hamon/algorithm/is_unique.hpp>
#include <hamon/algorithm/iter_swap.hpp>
#include <hamon/algorithm/lexicographical_compare.hpp>
#include <hamon/algorithm/lexicographical_compare_three_way.hpp>
#include <hamon/algorithm/lower_bound.hpp>
//#include <hamon/algorithm/make_heap.hpp>
#include <hamon/algorithm/max.hpp>
#include <hamon/algorithm/max_element.hpp>
//#include <hamon/algorithm/merge.hpp>
#include <hamon/algorithm/min.hpp>
#include <hamon/algorithm/min_element.hpp>
#include <hamon/algorithm/minmax.hpp>
#include <hamon/algorithm/minmax_element.hpp>
//#include <hamon/algorithm/mismatch.hpp>
#include <hamon/algorithm/move.hpp>
#include <hamon/algorithm/move_backward.hpp>
//#include <hamon/algorithm/next_permutation.hpp>
#include <hamon/algorithm/none_of.hpp>
//#include <hamon/algorithm/nth_element.hpp>
//#include <hamon/algorithm/partial_sort.hpp>
//#include <hamon/algorithm/partial_sort_copy.hpp>
//#include <hamon/algorithm/partition.hpp>
//#include <hamon/algorithm/partition_copy.hpp>
//#include <hamon/algorithm/partition_point.hpp>
//#include <hamon/algorithm/pop_heap.hpp>
//#include <hamon/algorithm/prev_permutation.hpp>
//#include <hamon/algorithm/push_heap.hpp>
//#include <hamon/algorithm/radix_sort.hpp>
#include <hamon/algorithm/ranges.hpp>
//#include <hamon/algorithm/remove.hpp>
//#include <hamon/algorithm/remove_copy.hpp>
//#include <hamon/algorithm/remove_copy_if.hpp>
//#include <hamon/algorithm/remove_if.hpp>
//#include <hamon/algorithm/replace.hpp>
//#include <hamon/algorithm/replace_copy.hpp>
//#include <hamon/algorithm/replace_copy_if.hpp>
//#include <hamon/algorithm/replace_if.hpp>
#include <hamon/algorithm/reverse.hpp>
#include <hamon/algorithm/reverse_copy.hpp>
//#include <hamon/algorithm/rotate.hpp>
//#include <hamon/algorithm/rotate_copy.hpp>
//#include <hamon/algorithm/sample.hpp>
//#include <hamon/algorithm/search.hpp>
//#include <hamon/algorithm/search_n.hpp>
//#include <hamon/algorithm/set_difference.hpp>
//#include <hamon/algorithm/set_intersection.hpp>
//#include <hamon/algorithm/set_symmetric_difference.hpp>
//#include <hamon/algorithm/set_union.hpp>
//#include <hamon/algorithm/shift_left.hpp>
//#include <hamon/algorithm/shift_right.hpp>
//#include <hamon/algorithm/shuffle.hpp>
//#include <hamon/algorithm/sort.hpp>
//#include <hamon/algorithm/sort_heap.hpp>
//#include <hamon/algorithm/stable_partition.hpp>
//#include <hamon/algorithm/stable_sort.hpp>
#include <hamon/algorithm/swap_ranges.hpp>
//#include <hamon/algorithm/transform.hpp>
//#include <hamon/algorithm/unique.hpp>
//#include <hamon/algorithm/unique_copy.hpp>
#include <hamon/algorithm/upper_bound.hpp>

#endif // HAMON_ALGORITHM_HPP
