/**
 *	@file	constexpr_test.hpp
 *
 *	@brief	
 */

#ifndef UNIT_TEST_COMMON_CONSTEXPR_TEST_HPP
#define UNIT_TEST_COMMON_CONSTEXPR_TEST_HPP

#include <hamon/config.hpp>

#  define HAMON_DETAIL_EXPECT_EQ_CT(x, y)	\
	static_assert((x) == (y), "failed assertion : EXPECT_EQ("#x", " #y")");	\
	EXPECT_EQ(x, y)

#  define HAMON_DETAIL_EXPECT_NE_CT(x, y)	\
	static_assert((x) != (y), "failed assertion : EXPECT_NE("#x", " #y")");	\
	EXPECT_NE(x, y)

#  define HAMON_DETAIL_EXPECT_TRUE_CT(x)	\
	static_assert((x), "failed assertion : EXPECT_TRUE("#x")");	\
	EXPECT_TRUE(x)

#  define HAMON_DETAIL_EXPECT_FALSE_CT(x)	\
	static_assert(!(x), "failed assertion : EXPECT_FALSE("#x")");	\
	EXPECT_FALSE(x)

#  define HAMON_DETAIL_EXPECT_NEAR_CT(x, y, abs_error)	\
	static_assert(hamon::fabs((x) - (y)) <= (abs_error), "failed assertion : EXPECT_NEAR("#x", " #y")");	\
	EXPECT_NEAR(x, y, abs_error)

#  define HAMON_DETAIL_EXPECT_EQ_RT(x, y)	\
	EXPECT_EQ(x, y)

#  define HAMON_DETAIL_EXPECT_NE_RT(x, y)	\
	EXPECT_NE(x, y)

#  define HAMON_DETAIL_EXPECT_TRUE_RT(x)	\
	EXPECT_TRUE(x)

#  define HAMON_DETAIL_EXPECT_FALSE_RT(x)	\
	EXPECT_FALSE(x)

#  define HAMON_DETAIL_EXPECT_NEAR_RT(x, y, abs_error)	\
	EXPECT_NEAR(x, y, abs_error)


#if defined(HAMON_HAS_CXX11_CONSTEXPR)

#  define HAMON_CXX11_CONSTEXPR_EXPECT_EQ		HAMON_DETAIL_EXPECT_EQ_CT
#  define HAMON_CXX11_CONSTEXPR_EXPECT_NE		HAMON_DETAIL_EXPECT_NE_CT
#  define HAMON_CXX11_CONSTEXPR_EXPECT_TRUE		HAMON_DETAIL_EXPECT_TRUE_CT
#  define HAMON_CXX11_CONSTEXPR_EXPECT_FALSE	HAMON_DETAIL_EXPECT_FALSE_CT
#  define HAMON_CXX11_CONSTEXPR_EXPECT_NEAR		HAMON_DETAIL_EXPECT_NEAR_CT

#else

#  define HAMON_CXX11_CONSTEXPR_EXPECT_EQ		HAMON_DETAIL_EXPECT_EQ_RT
#  define HAMON_CXX11_CONSTEXPR_EXPECT_NE		HAMON_DETAIL_EXPECT_NE_RT
#  define HAMON_CXX11_CONSTEXPR_EXPECT_TRUE		HAMON_DETAIL_EXPECT_TRUE_RT
#  define HAMON_CXX11_CONSTEXPR_EXPECT_FALSE	HAMON_DETAIL_EXPECT_FALSE_RT
#  define HAMON_CXX11_CONSTEXPR_EXPECT_NEAR		HAMON_DETAIL_EXPECT_NEAR_RT

#endif


#if defined(HAMON_HAS_CXX14_CONSTEXPR)

#  define HAMON_CXX14_CONSTEXPR_EXPECT_EQ		HAMON_DETAIL_EXPECT_EQ_CT
#  define HAMON_CXX14_CONSTEXPR_EXPECT_NE		HAMON_DETAIL_EXPECT_NE_CT
#  define HAMON_CXX14_CONSTEXPR_EXPECT_TRUE		HAMON_DETAIL_EXPECT_TRUE_CT
#  define HAMON_CXX14_CONSTEXPR_EXPECT_FALSE	HAMON_DETAIL_EXPECT_FALSE_CT
#  define HAMON_CXX14_CONSTEXPR_EXPECT_NEAR		HAMON_DETAIL_EXPECT_NEAR_CT

#else

#  define HAMON_CXX14_CONSTEXPR_EXPECT_EQ		HAMON_DETAIL_EXPECT_EQ_RT
#  define HAMON_CXX14_CONSTEXPR_EXPECT_NE		HAMON_DETAIL_EXPECT_NE_RT
#  define HAMON_CXX14_CONSTEXPR_EXPECT_TRUE		HAMON_DETAIL_EXPECT_TRUE_RT
#  define HAMON_CXX14_CONSTEXPR_EXPECT_FALSE	HAMON_DETAIL_EXPECT_FALSE_RT
#  define HAMON_CXX14_CONSTEXPR_EXPECT_NEAR		HAMON_DETAIL_EXPECT_NEAR_RT

#endif


#if defined(HAMON_HAS_CXX17_CONSTEXPR)

#  define HAMON_CXX17_CONSTEXPR_EXPECT_EQ		HAMON_DETAIL_EXPECT_EQ_CT
#  define HAMON_CXX17_CONSTEXPR_EXPECT_NE		HAMON_DETAIL_EXPECT_NE_CT
#  define HAMON_CXX17_CONSTEXPR_EXPECT_TRUE		HAMON_DETAIL_EXPECT_TRUE_CT
#  define HAMON_CXX17_CONSTEXPR_EXPECT_FALSE	HAMON_DETAIL_EXPECT_FALSE_CT
#  define HAMON_CXX17_CONSTEXPR_EXPECT_NEAR		HAMON_DETAIL_EXPECT_NEAR_CT

#else

#  define HAMON_CXX17_CONSTEXPR_EXPECT_EQ		HAMON_DETAIL_EXPECT_EQ_RT
#  define HAMON_CXX17_CONSTEXPR_EXPECT_NE		HAMON_DETAIL_EXPECT_NE_RT
#  define HAMON_CXX17_CONSTEXPR_EXPECT_TRUE		HAMON_DETAIL_EXPECT_TRUE_RT
#  define HAMON_CXX17_CONSTEXPR_EXPECT_FALSE	HAMON_DETAIL_EXPECT_FALSE_RT
#  define HAMON_CXX17_CONSTEXPR_EXPECT_NEAR		HAMON_DETAIL_EXPECT_NEAR_RT

#endif


#if defined(HAMON_HAS_CXX20_CONSTEXPR)

#  define HAMON_CXX20_CONSTEXPR_EXPECT_EQ		HAMON_DETAIL_EXPECT_EQ_CT
#  define HAMON_CXX20_CONSTEXPR_EXPECT_NE		HAMON_DETAIL_EXPECT_NE_CT
#  define HAMON_CXX20_CONSTEXPR_EXPECT_TRUE		HAMON_DETAIL_EXPECT_TRUE_CT
#  define HAMON_CXX20_CONSTEXPR_EXPECT_FALSE	HAMON_DETAIL_EXPECT_FALSE_CT
#  define HAMON_CXX20_CONSTEXPR_EXPECT_NEAR		HAMON_DETAIL_EXPECT_NEAR_CT

#else

#  define HAMON_CXX20_CONSTEXPR_EXPECT_EQ		HAMON_DETAIL_EXPECT_EQ_RT
#  define HAMON_CXX20_CONSTEXPR_EXPECT_NE		HAMON_DETAIL_EXPECT_NE_RT
#  define HAMON_CXX20_CONSTEXPR_EXPECT_TRUE		HAMON_DETAIL_EXPECT_TRUE_RT
#  define HAMON_CXX20_CONSTEXPR_EXPECT_FALSE	HAMON_DETAIL_EXPECT_FALSE_RT
#  define HAMON_CXX20_CONSTEXPR_EXPECT_NEAR		HAMON_DETAIL_EXPECT_NEAR_RT

#endif

#endif // UNIT_TEST_COMMON_CONSTEXPR_TEST_HPP
