/**
 *	@file	error.hpp
 *
 *	@brief
 */

#ifndef HAMON_PREPROCESSOR_DEBUG_ERROR_HPP
#define HAMON_PREPROCESSOR_DEBUG_ERROR_HPP
#
# include <hamon/preprocessor/cat.hpp>
# include <hamon/preprocessor/config/config.hpp>
#
# /* HAMON_PP_ERROR */
#
# if HAMON_PP_CONFIG_ERRORS
#    define HAMON_PP_ERROR(code) HAMON_PP_CAT(HAMON_PP_ERROR_, code)
# endif
#
# define HAMON_PP_ERROR_0x0000 HAMON_PP_ERROR(0x0000, HAMON_PP_INDEX_OUT_OF_BOUNDS)
# define HAMON_PP_ERROR_0x0001 HAMON_PP_ERROR(0x0001, HAMON_PP_WHILE_OVERFLOW)
# define HAMON_PP_ERROR_0x0002 HAMON_PP_ERROR(0x0002, HAMON_PP_FOR_OVERFLOW)
# define HAMON_PP_ERROR_0x0003 HAMON_PP_ERROR(0x0003, HAMON_PP_REPEAT_OVERFLOW)
# define HAMON_PP_ERROR_0x0004 HAMON_PP_ERROR(0x0004, HAMON_PP_LIST_FOLD_OVERFLOW)
# define HAMON_PP_ERROR_0x0005 HAMON_PP_ERROR(0x0005, HAMON_PP_SEQ_FOLD_OVERFLOW)
# define HAMON_PP_ERROR_0x0006 HAMON_PP_ERROR(0x0006, HAMON_PP_ARITHMETIC_OVERFLOW)
# define HAMON_PP_ERROR_0x0007 HAMON_PP_ERROR(0x0007, HAMON_PP_DIVISION_BY_ZERO)
#
#endif // HAMON_PREPROCESSOR_DEBUG_ERROR_HPP
