/**
 *	@file	unit_test_type_traits_is_nothrow_destructible.cpp
 *
 *	@brief	is_nothrow_destructible のテスト
 */

#include <hamon/type_traits/is_nothrow_destructible.hpp>
#include <hamon/config.hpp>
#include <gtest/gtest.h>
#include "type_traits_test_utility.hpp"

#if defined(HAMON_HAS_CXX14_VARIABLE_TEMPLATES)

#define HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(b, T)	\
	static_assert(hamon::is_nothrow_destructible_v<T>      == b, #T);	\
	static_assert(hamon::is_nothrow_destructible<T>::value == b, #T);	\
	static_assert(hamon::is_nothrow_destructible<T>{}()    == b, #T);	\
	static_assert(hamon::is_nothrow_destructible<T>{}      == b, #T)

#else

#define HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(b, T)	\
	static_assert(hamon::is_nothrow_destructible<T>::value == b, #T);	\
	static_assert(hamon::is_nothrow_destructible<T>{}()    == b, #T);	\
	static_assert(hamon::is_nothrow_destructible<T>{}      == b, #T)

#endif

namespace hamon_type_traits_test
{

namespace is_nothrow_destructible_test
{

// トリビアルなデストラクタを持つ
struct S1
{
	int n;
};

// 非トリビアルだが例外を投げないデストラクタを持つ
struct S2
{
	~S2() HAMON_NOEXCEPT_OR_NOTHROW;
};

// 非トリビアルだが例外を投げないデストラクタを持つクラスをメンバに持つ
struct S3
{
	S2 member;
};

// デストラクタが例外を投げる
struct S4
{
	~S4() HAMON_NOEXCEPT_IF(false);
};

// デストラクタを持たない
struct S5
{
	~S5() = delete;
};

// デストラクタが例外を投げるクラスをメンバに持つ
struct S6
{
	S4 member;
};

HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S1);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S2);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S3);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, S4);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, S5);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, S6);

HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,                 int);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  const          int);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,        volatile int);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  const volatile int);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  int*);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  int&);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  int&&);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  int[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, int[]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  int(&)[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  int(&)[]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  int(&&)[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  int(&&)[]);

HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false,                void);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, const          void);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false,       volatile void);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, const volatile void);

HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,                 UDT);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  const          UDT);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,        volatile UDT);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  const volatile UDT);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  UDT*);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  UDT&);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  UDT&&);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  UDT[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, UDT[]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  UDT(&)[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  UDT(&)[]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  UDT(&&)[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  UDT(&&)[]);

HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,                 S1);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  const          S1);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,        volatile S1);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  const volatile S1);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S1*);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S1&);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S1&&);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S1[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, S1[]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S1(&)[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S1(&)[]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S1(&&)[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S1(&&)[]);

HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,                 S2);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  const          S2);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,        volatile S2);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  const volatile S2);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S2*);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S2&);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S2&&);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S2[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, S2[]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S2(&)[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S2(&)[]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S2(&&)[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S2(&&)[]);

HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,                 S3);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  const          S3);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,        volatile S3);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  const volatile S3);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S3*);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S3&);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S3&&);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S3[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, S3[]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S3(&)[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S3(&)[]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S3(&&)[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S3(&&)[]);

HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false,                S4);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, const          S4);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false,       volatile S4);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, const volatile S4);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S4*);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S4&);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S4&&);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, S4[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, S4[]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S4(&)[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S4(&)[]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S4(&&)[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S4(&&)[]);

HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false,                S5);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, const          S5);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false,       volatile S5);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, const volatile S5);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S5*);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S5&);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S5&&);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, S5[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, S5[]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S5(&)[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S5(&)[]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S5(&&)[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S5(&&)[]);

HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false,                S6);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, const          S6);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false,       volatile S6);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, const volatile S6);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S6*);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S6&);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S6&&);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, S6[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, S6[]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S6(&)[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S6(&)[]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S6(&&)[2]);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  S6(&&)[]);

HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  test_abc1);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  test_abc2);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  test_abc3);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  test_concrete1);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  test_concrete2);

HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  f1);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  f2);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  f3);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  mf1);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  mf2);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  mf3);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  mf4);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  mp);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(true,  cmf);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, foo0_t);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, foo1_t);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, foo2_t);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, foo3_t);
HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST(false, foo4_t);

}	// namespace is_nothrow_destructible_test

}	// namespace hamon_type_traits_test

#undef HAMON_IS_NOTHROW_DESTRUCTIBLE_TEST
