/**
 *	@file	unit_test_qvm_quaternion_swizzle.cpp
 *
 *	@brief	swizzling のテスト
 */

#include <hamon/qvm/quaternion.hpp>
#include "constexpr_test.hpp"
#include "quaternion_test.hpp"
#include <type_traits>

namespace hamon_qvm_test
{

namespace quaternion_test
{

TYPED_TEST(QuaternionTest, SwizzleTest)
{
	using T = TypeParam;
	using quaternion = hamon::qvm::quaternion<T>;

	using vector4 = hamon::qvm::vector<T, 4>;
	using vector3 = hamon::qvm::vector<T, 3>;
	using vector2 = hamon::qvm::vector<T, 2>;

	HAMON_CONSTEXPR quaternion const q(1, 2, 3, 4);

	static_assert(std::is_same<vector4, decltype(q.xxxx())>::value, "");
	static_assert(std::is_same<vector3, decltype(q.xxx())>::value, "");
	static_assert(std::is_same<vector2, decltype(q.xx())>::value, "");

	{
//		HAMON_CONSTEXPR vector4 const t(q);		// error
		HAMON_CONSTEXPR vector4 const t(q.xyzw());
		HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 3, 4), t);
	}

	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 1, 1), q.xxxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 1, 2), q.xxxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 1, 3), q.xxxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 1, 4), q.xxxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 2, 1), q.xxyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 2, 2), q.xxyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 2, 3), q.xxyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 2, 4), q.xxyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 3, 1), q.xxzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 3, 2), q.xxzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 3, 3), q.xxzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 3, 4), q.xxzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 4, 1), q.xxwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 4, 2), q.xxwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 4, 3), q.xxwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 1, 4, 4), q.xxww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 1, 1), q.xyxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 1, 2), q.xyxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 1, 3), q.xyxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 1, 4), q.xyxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 2, 1), q.xyyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 2, 2), q.xyyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 2, 3), q.xyyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 2, 4), q.xyyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 3, 1), q.xyzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 3, 2), q.xyzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 3, 3), q.xyzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 3, 4), q.xyzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 4, 1), q.xywx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 4, 2), q.xywy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 4, 3), q.xywz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 2, 4, 4), q.xyww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 1, 1), q.xzxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 1, 2), q.xzxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 1, 3), q.xzxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 1, 4), q.xzxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 2, 1), q.xzyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 2, 2), q.xzyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 2, 3), q.xzyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 2, 4), q.xzyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 3, 1), q.xzzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 3, 2), q.xzzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 3, 3), q.xzzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 3, 4), q.xzzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 4, 1), q.xzwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 4, 2), q.xzwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 4, 3), q.xzwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 3, 4, 4), q.xzww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 1, 1), q.xwxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 1, 2), q.xwxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 1, 3), q.xwxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 1, 4), q.xwxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 2, 1), q.xwyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 2, 2), q.xwyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 2, 3), q.xwyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 2, 4), q.xwyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 3, 1), q.xwzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 3, 2), q.xwzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 3, 3), q.xwzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 3, 4), q.xwzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 4, 1), q.xwwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 4, 2), q.xwwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 4, 3), q.xwwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(1, 4, 4, 4), q.xwww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 1, 1), q.yxxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 1, 2), q.yxxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 1, 3), q.yxxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 1, 4), q.yxxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 2, 1), q.yxyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 2, 2), q.yxyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 2, 3), q.yxyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 2, 4), q.yxyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 3, 1), q.yxzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 3, 2), q.yxzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 3, 3), q.yxzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 3, 4), q.yxzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 4, 1), q.yxwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 4, 2), q.yxwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 4, 3), q.yxwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 1, 4, 4), q.yxww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 1, 1), q.yyxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 1, 2), q.yyxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 1, 3), q.yyxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 1, 4), q.yyxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 2, 1), q.yyyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 2, 2), q.yyyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 2, 3), q.yyyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 2, 4), q.yyyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 3, 1), q.yyzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 3, 2), q.yyzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 3, 3), q.yyzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 3, 4), q.yyzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 4, 1), q.yywx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 4, 2), q.yywy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 4, 3), q.yywz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 2, 4, 4), q.yyww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 1, 1), q.yzxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 1, 2), q.yzxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 1, 3), q.yzxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 1, 4), q.yzxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 2, 1), q.yzyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 2, 2), q.yzyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 2, 3), q.yzyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 2, 4), q.yzyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 3, 1), q.yzzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 3, 2), q.yzzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 3, 3), q.yzzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 3, 4), q.yzzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 4, 1), q.yzwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 4, 2), q.yzwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 4, 3), q.yzwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 3, 4, 4), q.yzww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 1, 1), q.ywxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 1, 2), q.ywxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 1, 3), q.ywxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 1, 4), q.ywxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 2, 1), q.ywyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 2, 2), q.ywyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 2, 3), q.ywyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 2, 4), q.ywyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 3, 1), q.ywzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 3, 2), q.ywzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 3, 3), q.ywzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 3, 4), q.ywzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 4, 1), q.ywwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 4, 2), q.ywwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 4, 3), q.ywwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(2, 4, 4, 4), q.ywww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 1, 1), q.zxxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 1, 2), q.zxxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 1, 3), q.zxxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 1, 4), q.zxxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 2, 1), q.zxyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 2, 2), q.zxyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 2, 3), q.zxyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 2, 4), q.zxyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 3, 1), q.zxzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 3, 2), q.zxzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 3, 3), q.zxzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 3, 4), q.zxzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 4, 1), q.zxwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 4, 2), q.zxwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 4, 3), q.zxwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 1, 4, 4), q.zxww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 1, 1), q.zyxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 1, 2), q.zyxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 1, 3), q.zyxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 1, 4), q.zyxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 2, 1), q.zyyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 2, 2), q.zyyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 2, 3), q.zyyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 2, 4), q.zyyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 3, 1), q.zyzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 3, 2), q.zyzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 3, 3), q.zyzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 3, 4), q.zyzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 4, 1), q.zywx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 4, 2), q.zywy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 4, 3), q.zywz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 2, 4, 4), q.zyww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 1, 1), q.zzxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 1, 2), q.zzxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 1, 3), q.zzxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 1, 4), q.zzxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 2, 1), q.zzyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 2, 2), q.zzyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 2, 3), q.zzyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 2, 4), q.zzyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 3, 1), q.zzzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 3, 2), q.zzzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 3, 3), q.zzzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 3, 4), q.zzzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 4, 1), q.zzwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 4, 2), q.zzwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 4, 3), q.zzwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 3, 4, 4), q.zzww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 1, 1), q.zwxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 1, 2), q.zwxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 1, 3), q.zwxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 1, 4), q.zwxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 2, 1), q.zwyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 2, 2), q.zwyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 2, 3), q.zwyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 2, 4), q.zwyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 3, 1), q.zwzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 3, 2), q.zwzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 3, 3), q.zwzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 3, 4), q.zwzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 4, 1), q.zwwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 4, 2), q.zwwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 4, 3), q.zwwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(3, 4, 4, 4), q.zwww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 1, 1), q.wxxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 1, 2), q.wxxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 1, 3), q.wxxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 1, 4), q.wxxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 2, 1), q.wxyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 2, 2), q.wxyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 2, 3), q.wxyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 2, 4), q.wxyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 3, 1), q.wxzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 3, 2), q.wxzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 3, 3), q.wxzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 3, 4), q.wxzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 4, 1), q.wxwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 4, 2), q.wxwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 4, 3), q.wxwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 1, 4, 4), q.wxww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 1, 1), q.wyxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 1, 2), q.wyxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 1, 3), q.wyxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 1, 4), q.wyxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 2, 1), q.wyyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 2, 2), q.wyyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 2, 3), q.wyyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 2, 4), q.wyyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 3, 1), q.wyzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 3, 2), q.wyzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 3, 3), q.wyzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 3, 4), q.wyzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 4, 1), q.wywx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 4, 2), q.wywy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 4, 3), q.wywz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 2, 4, 4), q.wyww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 1, 1), q.wzxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 1, 2), q.wzxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 1, 3), q.wzxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 1, 4), q.wzxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 2, 1), q.wzyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 2, 2), q.wzyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 2, 3), q.wzyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 2, 4), q.wzyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 3, 1), q.wzzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 3, 2), q.wzzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 3, 3), q.wzzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 3, 4), q.wzzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 4, 1), q.wzwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 4, 2), q.wzwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 4, 3), q.wzwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 3, 4, 4), q.wzww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 1, 1), q.wwxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 1, 2), q.wwxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 1, 3), q.wwxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 1, 4), q.wwxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 2, 1), q.wwyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 2, 2), q.wwyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 2, 3), q.wwyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 2, 4), q.wwyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 3, 1), q.wwzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 3, 2), q.wwzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 3, 3), q.wwzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 3, 4), q.wwzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 4, 1), q.wwwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 4, 2), q.wwwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 4, 3), q.wwwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector4(4, 4, 4, 4), q.wwww());

	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 1, 1), q.xxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 1, 2), q.xxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 1, 3), q.xxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 1, 4), q.xxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 2, 1), q.xyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 2, 2), q.xyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 2, 3), q.xyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 2, 4), q.xyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 3, 1), q.xzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 3, 2), q.xzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 3, 3), q.xzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 3, 4), q.xzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 4, 1), q.xwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 4, 2), q.xwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 4, 3), q.xwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(1, 4, 4), q.xww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 1, 1), q.yxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 1, 2), q.yxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 1, 3), q.yxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 1, 4), q.yxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 2, 1), q.yyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 2, 2), q.yyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 2, 3), q.yyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 2, 4), q.yyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 3, 1), q.yzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 3, 2), q.yzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 3, 3), q.yzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 3, 4), q.yzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 4, 1), q.ywx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 4, 2), q.ywy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 4, 3), q.ywz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(2, 4, 4), q.yww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 1, 1), q.zxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 1, 2), q.zxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 1, 3), q.zxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 1, 4), q.zxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 2, 1), q.zyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 2, 2), q.zyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 2, 3), q.zyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 2, 4), q.zyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 3, 1), q.zzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 3, 2), q.zzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 3, 3), q.zzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 3, 4), q.zzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 4, 1), q.zwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 4, 2), q.zwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 4, 3), q.zwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(3, 4, 4), q.zww());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 1, 1), q.wxx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 1, 2), q.wxy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 1, 3), q.wxz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 1, 4), q.wxw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 2, 1), q.wyx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 2, 2), q.wyy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 2, 3), q.wyz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 2, 4), q.wyw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 3, 1), q.wzx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 3, 2), q.wzy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 3, 3), q.wzz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 3, 4), q.wzw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 4, 1), q.wwx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 4, 2), q.wwy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 4, 3), q.wwz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector3(4, 4, 4), q.www());

	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(1, 1), q.xx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(1, 2), q.xy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(1, 3), q.xz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(1, 4), q.xw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(2, 1), q.yx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(2, 2), q.yy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(2, 3), q.yz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(2, 4), q.yw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(3, 1), q.zx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(3, 2), q.zy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(3, 3), q.zz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(3, 4), q.zw());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(4, 1), q.wx());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(4, 2), q.wy());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(4, 3), q.wz());
	HAMON_CXX11_CONSTEXPR_EXPECT_EQ(vector2(4, 4), q.ww());
}

}	// namespace quaternion_test

}	// namespace hamon_qvm_test
