function(add_sublibrary target flag dir lib)
  if (NOT TARGET Hamon::${lib})
    add_subdirectory(${dir}/${lib} ${CMAKE_CURRENT_BINARY_DIR}/${lib})
  endif()
  target_link_libraries(${target} ${flag} Hamon::${lib})
endfunction()

function(add_sublibraries target dir)
  cmake_parse_arguments(MYFUNC "" "" "PRIVATE;PUBLIC;INTERFACE" ${ARGN})
  foreach(LIB ${MYFUNC_PRIVATE})
    add_sublibrary(${target} PRIVATE ${dir} ${LIB})
  endforeach()
  foreach(LIB ${MYFUNC_PUBLIC})
    add_sublibrary(${target} PUBLIC ${dir} ${LIB})
  endforeach()
  foreach(LIB ${MYFUNC_INTERFACE})
    add_sublibrary(${target} INTERFACE ${dir} ${LIB})
  endforeach()
endfunction()
