name: algorithm

on:
  push:
    paths:
      - libs/algorithm/**
      - .github/workflows/algorithm.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/algorithm
