name: any

on:
  push:
    paths:
      - libs/any/**
      - .github/workflows/any.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/any
