name: array

on:
  push:
    paths:
      - libs/array/**
      - .github/workflows/array.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/array
