name: atomic

on:
  push:
    paths:
      - libs/atomic/**
      - .github/workflows/atomic.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/atomic
