name: base64

on:
  push:
    paths:
      - libs/base64/**
      - .github/workflows/base64.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/base64
