name: bit

on:
  push:
    paths:
      - libs/bit/**
      - .github/workflows/bit.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/bit
