name: bitflags

on:
  push:
    paths:
      - libs/bitflags/**
      - .github/workflows/bitflags.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/bitflags
