name: bitset

on:
  push:
    paths:
      - libs/bitset/**
      - .github/workflows/bitset.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/bitset
