name: build

on:
  workflow_call:
    inputs:
      src_dir:
        required: true
        type: string
      unity_build:
        default: 'OFF'
        required: false
        type: string
      disable_precompile_headers:
        default: 'OFF'
        required: false
        type: string

env:
  SRC_DIR: ${{github.workspace}}/${{inputs.src_dir}}
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  windows-test:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-2022, generator: "Visual Studio 17 2022" }
        - { os: windows-2019, generator: "Visual Studio 16 2019" }
        architecture: [x64, Win32]
        cxx_standard: [14, 17, 20, 23]
        build_type: [Debug, Release]
        exclude:
          - config: { generator: "Visual Studio 16 2019" }
            cxx_standard: 23
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Configure CMake
        run: |
          cmake "$SRC_DIR" \
            -B "$BUILD_DIR" \
            -G "${{matrix.config.generator}}" \
            -A "${{matrix.architecture}}" \
            -DCMAKE_UNITY_BUILD="${{inputs.unity_build}}" \
            -DCMAKE_DISABLE_PRECOMPILE_HEADERS="${{inputs.disable_precompile_headers}}" \
            -DCMAKE_CXX_STANDARD="${{matrix.cxx_standard}}" \
            -DCMAKE_BUILD_TYPE="${{matrix.build_type}}"
      - name: Build
        run: cmake --build "$BUILD_DIR" --config ${{matrix.build_type}}
      - name: Test
        working-directory: ${{env.BUILD_DIR}}
        run: ctest -j 4 -C ${{matrix.build_type}}

  ubuntu-test:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: ubuntu-24.04, cc: "gcc-14",   cxx: "g++-14" }
        - { os: ubuntu-24.04, cc: "gcc-13",   cxx: "g++-13" }
        - { os: ubuntu-24.04, cc: "gcc-12",   cxx: "g++-12" }
        - { os: ubuntu-22.04, cc: "gcc-11",   cxx: "g++-11" }
        - { os: ubuntu-22.04, cc: "gcc-10",   cxx: "g++-10" }
        - { os: ubuntu-20.04, cc: "gcc-9",    cxx: "g++-9"  }
        - { os: ubuntu-24.04, cc: "clang-18", cxx: "clang++-18" }
        - { os: ubuntu-24.04, cc: "clang-17", cxx: "clang++-17" }
        - { os: ubuntu-24.04, cc: "clang-16", cxx: "clang++-16" }
        - { os: ubuntu-22.04, cc: "clang-15", cxx: "clang++-15" }
        - { os: ubuntu-22.04, cc: "clang-14", cxx: "clang++-14" }
        - { os: ubuntu-22.04, cc: "clang-13", cxx: "clang++-13" }
        - { os: ubuntu-20.04, cc: "clang-12", cxx: "clang++-12" }
        - { os: ubuntu-20.04, cc: "clang-11", cxx: "clang++-11" }
        - { os: ubuntu-20.04, cc: "clang-10", cxx: "clang++-10" }
        cxx_standard: [11, 14, 17, 20, 23]
        build_type: [Debug, Release]
        exclude:
          - config: { cxx: "g++-10" }
            cxx_standard: 23
          - config: { cxx: "g++-9" }
            cxx_standard: 23
          - config: { cxx: "clang++-15" }
            cxx_standard: 23
          - config: { cxx: "clang++-14" }
            cxx_standard: 23
          - config: { cxx: "clang++-13" }
            cxx_standard: 23
          - config: { cxx: "clang++-12" }
            cxx_standard: 23
          - config: { cxx: "clang++-11" }
            cxx_standard: 23
          - config: { cxx: "clang++-10" }
            cxx_standard: 23
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Configure CMake
        run: |
          cmake "$SRC_DIR" \
            -B "$BUILD_DIR" \
            -DCMAKE_UNITY_BUILD="${{inputs.unity_build}}" \
            -DCMAKE_DISABLE_PRECOMPILE_HEADERS="${{inputs.disable_precompile_headers}}" \
            -DCMAKE_CXX_COMPILER=${{matrix.config.cxx}} \
            -DCMAKE_C_COMPILER=${{matrix.config.cc}} \
            -DCMAKE_CXX_STANDARD=${{matrix.cxx_standard}} \
            -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
      - name: Build
        run: cmake --build "$BUILD_DIR" --config ${{matrix.build_type}}
      - name: Test
        working-directory: ${{env.BUILD_DIR}}
        run: ctest -j 4 -C ${{matrix.build_type}}

  macos-test:
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: macos-14, cc: "clang", cxx: "clang++" }
        - { os: macos-13, cc: "clang", cxx: "clang++" }
        - { os: macos-12, cc: "clang", cxx: "clang++" }
        cxx_standard: [11, 14, 17, 20, 23]
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Configure CMake
        run: |
          cmake "$SRC_DIR" \
            -B "$BUILD_DIR" \
            -DCMAKE_UNITY_BUILD="${{inputs.unity_build}}" \
            -DCMAKE_DISABLE_PRECOMPILE_HEADERS="${{inputs.disable_precompile_headers}}" \
            -DCMAKE_CXX_COMPILER=${{matrix.config.cxx}} \
            -DCMAKE_C_COMPILER=${{matrix.config.cc}} \
            -DCMAKE_CXX_STANDARD=${{matrix.cxx_standard}} \
            -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
      - name: Build
        run: cmake --build "$BUILD_DIR" --config ${{matrix.build_type}}
      - name: Test
        working-directory: ${{env.BUILD_DIR}}
        run: ctest -j 4 -C ${{matrix.build_type}}

