name: chrono

on:
  push:
    paths:
      - libs/chrono/**
      - .github/workflows/chrono.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/chrono
