name: cmath

on:
  push:
    paths:
      - libs/cmath/**
      - .github/workflows/cmath.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/cmath
