name: compare

on:
  push:
    paths:
      - libs/compare/**
      - .github/workflows/compare.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/compare
