name: complex

on:
  push:
    paths:
      - libs/complex/**
      - .github/workflows/complex.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/complex
