name: config

on:
  push:
    paths:
      - libs/config/**
      - .github/workflows/config.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/config
