name: core

on:
  push:
    paths:
      - libs/**
      - .github/workflows/core.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: ''
      unity_build: 'ON'
