name: cstddef

on:
  push:
    paths:
      - libs/cstddef/**
      - .github/workflows/cstddef.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/cstddef
