name: deque

on:
  push:
    paths:
      - libs/deque/**
      - .github/workflows/deque.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/deque
