name: expected

on:
  push:
    paths:
      - libs/expected/**
      - .github/workflows/expected.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/expected
