name: forward_list

on:
  push:
    paths:
      - libs/forward_list/**
      - .github/workflows/forward_list.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/forward_list
