name: functional

on:
  push:
    paths:
      - libs/functional/**
      - .github/workflows/functional.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/functional
