name: iterator

on:
  push:
    paths:
      - libs/iterator/**
      - .github/workflows/iterator.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/iterator
