name: limits

on:
  push:
    paths:
      - libs/limits/**
      - .github/workflows/limits.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/limits
