name: list

on:
  push:
    paths:
      - libs/list/**
      - .github/workflows/list.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/list
