name: numbers

on:
  push:
    paths:
      - libs/numbers/**
      - .github/workflows/numbers.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/numbers
