name: numeric

on:
  push:
    paths:
      - libs/numeric/**
      - .github/workflows/numeric.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/numeric
