name: optional

on:
  push:
    paths:
      - libs/optional/**
      - .github/workflows/optional.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/optional
