name: pair

on:
  push:
    paths:
      - libs/pair/**
      - .github/workflows/pair.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/pair
