name: qvm

on:
  push:
    paths:
      - libs/qvm/**
      - .github/workflows/qvm.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/qvm
