name: ranges

on:
  push:
    paths:
      - libs/ranges/**
      - .github/workflows/ranges.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/ranges
