name: serialization

on:
  push:
    paths:
      - libs/serialization/**
      - .github/workflows/serialization.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/serialization
