name: set

on:
  push:
    paths:
      - libs/set/**
      - .github/workflows/set.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/set
