name: shared_mutex

on:
  push:
    paths:
      - libs/shared_mutex/**
      - .github/workflows/shared_mutex.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/shared_mutex
