name: span

on:
  push:
    paths:
      - libs/span/**
      - .github/workflows/span.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/span
