name: string

on:
  push:
    paths:
      - libs/string/**
      - .github/workflows/string.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/string
