name: system_error

on:
  push:
    paths:
      - libs/system_error/**
      - .github/workflows/system_error.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/system_error
