name: tuple

on:
  push:
    paths:
      - libs/tuple/**
      - .github/workflows/tuple.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/tuple
