name: type_info

on:
  push:
    paths:
      - libs/type_info/**
      - .github/workflows/type_info.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/type_info
