name: units

on:
  push:
    paths:
      - libs/units/**
      - .github/workflows/units.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/units
