name: unordered_set

on:
  push:
    paths:
      - libs/unordered_set/**
      - .github/workflows/unordered_set.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/unordered_set
