name: utility

on:
  push:
    paths:
      - libs/utility/**
      - .github/workflows/utility.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/utility
