name: variant

on:
  push:
    paths:
      - libs/variant/**
      - .github/workflows/variant.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/variant
