name: vector

on:
  push:
    paths:
      - libs/vector/**
      - .github/workflows/vector.yml
      - .github/workflows/build.yml

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      src_dir: libs/vector
